### ISSUE TITLE
Bot does not seem to honor {keep}.

### ISSUE THREAD

**Issue by ganarajpr** [silentrob/superscript#100]
```
+ hi
- Hi. Welcome to macy's. 
^ How can I address you as?

  + *1
  % * How can I address you as?  
  - ^addCustomer(<cap>).
  ^ Hi <cap>. Can I take your order?

    + (*)
    % * Can I take your order?
    - ordered <cap>. ^storeOrder(<cap>) . anything else ?
+(*)
% * anything else ?
- {keep} ordered <cap>. ^storeOrder(<cap>) . anything else ?

+ done
- thank you I will place your order.
```

The bot does not seem to honor keep. 
From the above conversation I am expecting the bot to keep taking orders until the user says 'done'. But the bot seems to 'exhaust' taking order after 2 attempts. How do we fix this ?

**Comment by silentrob** [comment]
If you can create a simple test that reproduces the problem, I can que it up and fix it.

**Comment by silentrob** [comment]
Okay. Ive created a test and see the nature of the problem.
This isn't quite related to keep, we actually don't get that far. In conversations like this, we always try to match forward, but once there is no more matches we don't walk back up the tree, we reset back to the Random Topic (in your case).

I will see if the fix is easy.

**Comment by silentrob** [comment]
So the problem is we don't have a reference to the parent (gambit) from the child reply. I will need to update the model to enforce that relationship, and add some recursion to walk up the parents searching for gambits to match, until we hit null (the topic).

**Comment by silentrob** [comment]
Okay, Ive got this working in a branch now, and the first thing Ive noticed is `*` in conversation threads have the same weight as topic level `*` wildcards. Your example above has 3 of them. Im still investigating, but it almost might make sense to have a break out and negate that behaviour somehow. 
I will push the code for you to play with.

**Comment by silentrob** [comment]
See https://github.com/silentrob/superscript/tree/walkupconvo

**Comment by dcsan** [comment]
could you set different topics and then goto the other topic when order is done?
having multiple wildcards in one topic seems complex.

also related - i found the default lack of keep and the arbitrary feeling rules for picking and switching topics made creating deterministic bots really difficult. it maybe better for simulating how real people act ("hey i got bored and changed the topic to something else maybe"), but its hard for creating predictable, if repetitive bots. maybe its the difference between winning a turing test and creating a utility bot for a purpose which people know is a bot, but want something specific to be done. like applescript vs javascript, sometimes being too english-like makes it hard to use.

**Comment by silentrob** [comment]
@dcsan I think there are other tools that might work better for you. RiveScript is designed to be much more deterministic, as is Hubot https://hubot.github.com/.  The goal of SuperScript is to create human like chat bots - that goal hasn't changed.

**Comment by mariusursache** [comment]
@silentrob,
> Okay, Ive got this working in a branch now, and the first thing Ive noticed is * in conversation threads have the same weight as topic level * wildcards. Your example above has 3 of them. Im still investigating, but it almost might make sense to have a break out and negate that behaviour somehow. 
I will push the code for you to play with.

Is this working better right now? Or should we use weighting in inputs?

**Comment by silentrob** [comment]
This should be reviewd. I think it works now.
