### ISSUE TITLE
Investigate jison/PEG as a new parsing interface. 

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#101]
I believe this would replace Regular expressions under the hood completely. 

http://zaach.github.io/jison/ 
http://pegjs.org/

**Comment by silentrob** [comment]
As suggested in GH-99

Initial review, Peg seems more current, code, docs and project, Jison is faster and a little out of date.
Jison powers CoffeeScript.

**Comment by ganarajpr** [comment]
Jison has https://github.com/nolanlawson/jison-debugger

**Comment by ganarajpr** [comment]
I will look into creating a PEG grammar for parsing.

**Comment by silentrob** [comment]
I can see some advantages of using a grammer to replace the script file, and could envision there being one for a trigger and one for reply nested inside a more general topic grammar.

Where things break down is how it would be useful behold that. I think Im missing something key. Internally each gambit has a trigger to match on. Essentially a regular expression. It would be nice to remove that, but Im not sure how PEG or Jison would help do that.

It is also worth noting, that for people who really don't want to get too hung up in the syntax, the web interface (editor) might be a good happy medium.

**Comment by ganarajpr** [comment]
Try this : 


```

{
  function makeInteger(o) {
    return parseInt(o.join(""), 10);
  }
}

start
  = trigger
  
star 
  = "*"
  
starn
    = "*" val:integer { return { type : "starn", value : val }; }  

starupton
    = "*~" val:integer { return { type : "starupton", value : val }; }

starminmax
    = "*(" ws* min:integer ws* "," ws* max:integer ws* ")" { return { type : "minmax", val:{ min: min, max: max } }; }

string
    = str:[a-zA-Z]+ { return { type: "string", val: str.join("")}; }

triggerTokens
    = starn:starn ws* { return starn;}
    / starupton:starupton ws* { return starupton;}
    / starminmax:starminmax ws* { return starminmax;}
    / st:star ws* { return {type : "star", value : "*" }; }
    / integer:integer ws* { return integer;}
    / string:string ws* { return string;}

    
trigger 
    = "+" ws+ trigs:triggerTokens+ ws* nl* { return trigs;}
     
integer "integer"
  = digits:[0-9]+ { return makeInteger(digits); }


ws "whitespace" = [ \t]

nl "newline" = [\n\r]


```

This is a peg grammar I just wrote for triggers ( does not yet handle alternates and optionals ) - but from my initial tests seem to handle the "*" value entries. 

What this possibly gives you is a nice tokenization mechanism - and perhaps a fast iteration - especially when your DSL's grammar is evolving. 

Let me know if you want me to continue on this.

**Comment by silentrob** [comment]
This looks great. I will play with it this weekend. I'm traveling today, and I hate writing code on planes.

**Comment by silentrob** [comment]
Moved to (https://github.com/silentrob/ss-parser/issues/1)
