### ISSUE TITLE
Topic Importer changes have broken examples

### ISSUE THREAD

**Issue by ganarajpr** [silentrob/superscript#103]
The changes in here : 

https://github.com/silentrob/superscript/commit/752116575eadb19762a2cbe216388a588792da79#diff-29937e29bbc771835501882d9974a0fcL30

has broken the examples ( bot clients ) - because the bot clients rely on the `TopicSystem` to have a function called `importer`

**Comment by silentrob** [comment]
Good catch, sorry about that.
