### ISSUE TITLE
Quickstart on windows 

### ISSUE THREAD

**Issue by CarbonMan** [silentrob/superscript#104]
After following the instructions to start the superscript-editor I am getting;
Error connecting to the MongoDB -- [Error: failed to connect to [localhost:27017]]

Mongodb is running as a service. No errors in its logs it states "waiting for connections on port 27017" I noticed within the code that the default db is testbot, so I created one but it didn't help.

I have gone through the telnet client area of the quickstart and that is working. It is just superscript-editor that won't start.

**Comment by silentrob** [comment]
I'm sorry to hear you are having problems. I have not tested the system extensively on windows, but would would to get to the bottom of it. Which version of windows are you using?

**Comment by CarbonMan** [comment]
Thanks for the reply. I am on Windows 8.1 64 bit

**Comment by CarbonMan** [comment]
I have resolved it. Changing;
var options = { server: { socketOptions: { keepAlive: 1 } } };
to
var options = {};
in app.js fixed it. So it might be an issue with Mongo on Windows??
