### ISSUE TITLE
Add index to reply field on replies collection

### ISSUE THREAD

**Issue by noppanit** [silentrob/superscript#105]
It would be nice if I could perform text search on `replies` collection. Would it be possible if I do a PR for this one?

https://github.com/silentrob/superscript/blob/master/lib/topics/reply.js#L11

**Comment by silentrob** [comment]
Absolutely. I'm not sure why I didn't add that to begin with. 

Having said that, can you walk me through your use case.

**Comment by noppanit** [comment]
My use case is. People ask for a machine on Slack channel a lot. Instead of having everyone saying it's ok to use the machine. 

I was thinking of having the bot to check a particular keyword in the database. Then the bot can reply who's the last person mentioned the keyword. To do that I need to use `db.replies.find( { $text: { $search: "machine" } } )` which requires an index on the collection. 

Do you think this makes sense?

**Comment by silentrob** [comment]
I think I follow you. The replies however are the canned responses the bot can say.

If you want to know who asked the bot for something or how the bot replied, you need to check the user model / history. 

Does that make sense? I'm afk at the moment or I would show your the line / code that does that.

**Comment by noppanit** [comment]
Oh, that makes more sense. Yes can you please show me that line and does `users` collection has index for full-text search? If not do you want me to make a PR for that?

**Comment by silentrob** [comment]
So the line you want to look at is here - https://github.com/silentrob/superscript/blob/master/lib/users.js#L28

I should point out that you only get the last 15 messages and there is no index on it.
There is also 2 public interfaces for users here.
https://github.com/silentrob/superscript/blob/master/index.js#L263-L273.

Lastly, if you are feeling brave. I wrote a utility that walks the users history searching for things (nouns, names etc.) it might be worth looking at too. It is designed to be called from within a plugin function.

https://github.com/silentrob/superscript/blob/master/lib/history.js

I would happily take a pull request to make the system better in anyway! Thanks for your interest in Bots and SuperScript.

**Comment by noppanit** [comment]
I have one question. I have decided to go a different path. I'm going to use plugin instead and I'm going to create a new collection in the database that way it's going to be easier and faster than fetching data from history every time.

Here's my code. However, I don't see the way to parse `mongoose` object to the plugin. Am I missing something? Can I call parse any object from `server.js` to the plugin? 

```
var StagingUtil = function(mongoose) {
	var CheckStagingSchema = mongoose.Schema({
		user: String,
		createdAt: { type: Date, default: Date.now }
	});

	this.CheckStaging = mongoose.model('CheckStaging', CheckStagingSchema);

}

StagingUtil.prototype.lastPersonAskedForInHour = function(user, message, callback) {
	var self = this;
	if(message.indexOf('staging') > -1) { // This is going to be deleted because I'm going to use Superscript instead.
	
		this.CheckStaging.findOne(function(err, record) {
			if (err) return console.error(err);

			if(record) {
				record.user = user;
				record.createdAt = new Date();
				record.save();
				callback(record);
			} else {
				var lastPersonMentionedStaging = new self.CheckStaging({
					user: user
				}).save(function(err, lastPersonMentionedStaging) {				
					if (err) return console.error(err);
					
					callback(lastPersonMentionedStaging);
				});
			}
		});

	}
}


```

**Comment by silentrob** [comment]
Always happy to help out. So if you want some custom function (or object) available from within a plugin you just need to pass it into the bot options. 

Here is an example.

    var superscript = require("superscript");

    var options = {};
    options['factSystem'] = factSystem;
    options['mongoose'] = mongoose;
    options['scope'] = {
      'customFunction': function(a, b) { return a + b }
    }

    new superscript(options, function(err, bot) {
       // bot stuff, request, reply
    });


So the key here is the 'scope' key will mixin to the plugins.
Then from your custom plugin you have the function available. ie: `this.customFunction()` 

Here is the line that calls the plugin.
https://github.com/silentrob/superscript/blob/master/lib/processtags.js#L51-L52

**Comment by silentrob** [comment]
Im going to close this issue, but if you still have more questions, please re-open or create a new issue.
