### ISSUE TITLE
Updated documentation

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript#106]
I have started a draft documentation here, will add more as I am experimenting with the editor: https://github.com/silentrob/superscript-editor/wiki/Documentation

Questions:

1. Should it be in this repo, instead (wiki)?
2. Anyone else (except @silentrob) interested in helping?

**Comment by silentrob** [comment]
Super cool!
I also have the superscriptjs.com site open sourced - https://github.com/silentrob/superscriptjs.com
We may want to have a line in what should be in the wiki (editor stuff) and the more general superscript stuff on the site... 

Or perhaps the site can remain more marketing like and the docs can live in the wiki.
Anyway, this is all great, thanks for pitching in and I will tackle this issue that crop up.

**Comment by ganarajpr** [comment]
A video tutorial would be awesome too - since we are doing a demo of the superscript editor? Anyone thinking of doing that ? 

I personally dont use the superscript-editor .. so I dont have much experience using it.

**Comment by silentrob** [comment]
This is not a bad idea. I think it might make sense to add this once the UI settles down a little more. It is still in active development.

**Comment by mariusursache** [comment]
The documentation is in progress at https://docs.google.com/document/d/1tk-Jk4YK1k23dbUspJgOsV6SrQS3BCiw4iczVHoKu0k/edit?usp=sharing (easier to make changes/adjust things/comment at this stage, than .md files or the wiki—will transfer it to the Wiki once it's closer to final, right now it still misses a lot of things).
