### ISSUE TITLE
Greedy gambits prioritized when matching

### ISSUE THREAD

**Issue by karovski** [silentrob/superscript#108]
Currently a greedy gambit like `*` will override other less greedy gambits like `hey *`. This makes it hard to catch broader messages after specific messages are not matched.

Is the sorting TODO relevant [here] (https://github.com/silentrob/superscript/blob/master/lib/topics/index.js)?

Also, I checked out the sorting logic and poked around the editor, however all I found was that the quick sort in the editor was crashing it (referenced in https://github.com/silentrob/superscript-editor/issues/14) where it was mentioned that this is a bug/issued and afterwards the quick sort was removed from the editor in https://github.com/silentrob/superscript-editor/commit/8e07694eb3ba2b84bcacf98de22a9618a849e47c

Is there a way to sort gambits by weight at the moment?

**Comment by silentrob** [comment]
Yes by using `{weight=XX}` in your input it will rank those higher than the ones without. I'm also working on adding a manual drag and drop sort to the editor. I started that last night actually. 

The sorting algorithm is designed to solve this problem already providing it is being called. (I need to double check that) 

The third issue is sorting sub replies within a given gambit but we can address that after the other two cases are working properly.

**Comment by mariusursache** [comment]
Does weight also work in replies prioritization like rivescript?

**Comment by silentrob** [comment]
No, the reply system is completely overhauled and I didn't see much value in having a weighted reply.

**Comment by lucasfcosta** [comment]
@silentrob So an input like: `* woman * {weight=10}` would match instead of `[*]`?
Am I right? I tried the example above using the web editor and it didn't work.

**Comment by silentrob** [comment]
I think this issue was related to the editor and not superscript itself.. if this is still an issue, please let me know and we can reopen and file as a bug.
