### ISSUE TITLE
Conceptual approach to developing new functionality

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript#109]
Me and my colleagues are implementing the bot in an app that is an "interviewer" for the user (opposed to the usual bot implementation, where the bot mostly replies to the user questions). There are a few areas where we'd love to hear your thoughts or suggestions on how to approach this conceptually:

1. **Self-initiated replies**, meaning that at the beginning of a topic (for example), the bot will start the conversation without the user writing anything. It has been referred (I think) also here: https://github.com/silentrob/superscript/issues/24. Maybe a generic trigger such as *:1 (or whatever) that is greedier than *?
2. **Self-learning loops**: if a user asks the bot something, the bot will say *"Sorry, I don't know what to reply. Can you teach me what to reply to this?"*. Then the user offers an answer, which the user records. Not sure if the best way is to keep this as user facts, or auto-generate topics/gambits based on the initial question from user and the subsequent reply.
3. **Recalling user replies**. Initially the bot is an interviewer, and the user the interviewee. Later on, we want to switch the context (and the bot to "impersonate" the user). How could we store initial user replies and recall them when the bot has to "impersonate" the user? Any suggestions? User facts? Auto-generated topics?

:-)

**Comment by silentrob** [comment]
Aweome! This is a great use-case for Superscript. I would like to work through these points with you. 
Would you be interested in jumping into a chat or want to setup a call sometime to discuss these in more detail?
