### ISSUE TITLE
npm install error on iojs

### ISSUE THREAD

**Issue by hipitihop** [silentrob/superscript#112]
`npm install superscript -g` produces following terminal error however ss appears to work:
```
CXX(target) Release/obj.target/leveldown/src/database.o
../src/database.cc: In static member function ‘static void leveldown::Database::Iterator(const v8::FunctionCallbackInfo<v8::Value>&)’:
../src/database.cc:552:35: warning: ‘void node::FatalException(const v8::TryCatch&)’ is deprecated (declared at /home/ubuntu/.node-gyp/2.3.0/src/node.h:282): Use FatalException(isolate, ...) [-Wdeprecated-declarations]
     node::FatalException(try_catch);
```

Environment: Ubuntu server 14.04 LTS using iojs-v2.3.0 via nvm.

**Comment by silentrob** [comment]
I have not tested superscript on IO.js. It is tested and works fine on node 0.10.x and 0.12.x on mac and ubuntu. If you would like to add support for IO.js please submit a PR.
