### ISSUE TITLE
Telnet server bot, adding data.json in mongo superscriptDB not updating it.

### ISSUE THREAD

**Issue by volumetric** [silentrob/superscript#114]
I am running a telnet client based bot, and i am developing Superscript script for my bot. i am noticing that the telnet server.js app for the bot, stores the data from data.json file in mongodb DB called superscriptDB and everytime, i start the application, after re-compiling my main.ss to a new data.json, it adds all the gambits, topics and replies on top of the previous ones, onto the mongodb DB.

Is this supposed to be the correct behavior, as any updates that i make in main.ss and hence data.json should replace the old one, not add on top of it.

As the bot is generating the response from superscriptDB, when i talk to him.

Would be very useful for my development, if someone can help me figure this out. Thanks.

**Comment by ganarajpr** [comment]
I believe this is a duplicate of #95 . I have a temporary fix for this in that thread until a more perm fix is done.

**Comment by volumetric** [comment]
Thanks @ganarajpr Will use your temp fix for now.
