### ISSUE TITLE
^respond(topic) in replies is escaped

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript#117]
From what I remember you also discovered this when testing https://github.com/silentrob/superscript-editor/issues/19. On the other hand, other  plugins (I tried ^getSeason()) seem to work.

The gambit:

![image](https://cloud.githubusercontent.com/assets/867133/8431036/33d3a63a-1f3f-11e5-98c5-4aada51cfc5b.png)

The test:

![image](https://cloud.githubusercontent.com/assets/867133/8431044/440ee118-1f3f-11e5-9a48-e1ed8b8e2e5b.png)

This is rather critical.

**Comment by mariusursache** [comment]
same thing for topicRedirect(test-topic)

**Comment by mariusursache** [comment]
This is critical, might be an editor issue, not sure.

**Comment by mariusursache** [comment]
Any updates here?

**Comment by silentrob** [comment]
I think this is just in the editor. I will address it there.

**Comment by mariusursache** [comment]
Moved to editor.
