### ISSUE TITLE
"Really" not caught by generic wildcard or question wildcard

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript#118]
Defined two gambits in random topic:
* generic question wildcard ( ? * / I don't know )
* generic wildcard ( * / I don't understand )

![image](https://cloud.githubusercontent.com/assets/867133/8435137/540a6bfa-1f58-11e5-9c4e-219f8411b989.png)

When I ask (with or without question) 'Really?', the system does not find it. Might be an odd case of normalizing 'Really'?

![image](https://cloud.githubusercontent.com/assets/867133/8435175/8f72700c-1f58-11e5-9bfe-8d8a5ae383d9.png)

**Comment by mariusursache** [comment]
Just realized that "really" is "eliminated" in the normalization process, and in this case the input becomes blank—but this should still be processed by the generic wildcard *, no?

**Comment by mariusursache** [comment]
Suggested solution: create "mandatory" keywords which do not get normalized or filtered out, and are matched exactly as they are:

```
+ * \colour\ *
- Have you recently spent time in London, dude?
```

could match *What colour is your car* but not *What color is your car*, and would also  ease the use of natural conversation bits like *Really* or *quite* which get filtered out.

**Comment by Rajan** [comment]
I faced the same thing.

**Comment by mariusursache** [comment]
Test and see if it works as an alternate: *+ (really)*
"Really" is filtered out in the normalizing process.

**Comment by silentrob** [comment]
Here is the problem. This should be removed.
https://github.com/silentrob/normalizer/blob/master/data/substitutes.txt#L1262

**Comment by silentrob** [comment]
This should be resolved now.

**Comment by Rajan** [comment]
Thank you Rob. I've forked normalizer.
