### ISSUE TITLE
Editor vs raw SS files

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript#121]
The switch from raw SS files to the editor, while opening new doors, causes several issues. Since there's a handful of people who fancy SuperScript, I thought that sharing experiences/suggestions and thoughts on this could be helpful (as I am trying to update the documentation and want to make it relevant for everyone).

What are you currently using? Thoughts? Examples you can share?

/CC @volumetric @kgao @hipitihop @noppanit @ganarajpr @owenhindley @karovski @rayearl

**Comment by owenhindley** [comment]
For our project (which should hopefully see the light of day this year sometime!) we exclusively did our editing in-script, using a grunt script to re-compile and restart the server(s) every time there was a change to the .ss file. 

It's been a little while since I looked at the SS editor (maybe it's changed) but for our particular case - creating a narrative, story-driven conversation - it was important to be able to look at an entire bot's 'script' all at once, where topics became part of a flow rather than something to move randomly between.

That said, being able to update the database and test on the fly should make for much faster development, rather than having to parse .ss files every time.

**Comment by ganarajpr** [comment]
For me it was only the ss files. I never got to using the editor. It did not work for me for some reasons or probably I did not give it enough consideration.

Because superscript works with mongodb ( and writes to it ), I have had to come up with a script to clear the db every time I need to recompile the ss script..

**Comment by mariusursache** [comment]
I would really appreciate if you could share a script for importing SS files, we're currently having trouble with that... :-/

**Comment by ganarajpr** [comment]
I have put more details and source of the script I wrote in #95 .

**Comment by mariusursache** [comment]
Thanks @ganarajpr! :-)

**Comment by volumetric** [comment]
For a project work, I also prefer to work with the ss file directly and having a better and faster workflow, in terms of compiling and updating the DB with the generated data.json file, instead of working with a web UI. I think web UI is great if you are trying to test out things and want to learn some features of ss or maybe in the future, want to experiment with some new to add in. But for any organized development, i prefer what @ganarajpr has done and using a similar script.

**Comment by silentrob** [comment]
Thanks for the feedback. The web interface is still pretty new and needs a lot more attention. Just for background, as my bot grew from ~200 gambits to ~2000 the reloading the conversation model creeped up to 2+ minutes, and while I expieremented with various types of caching I knew that was only a stop-gap. 

I felt the only way to really improve the authorng expierence was by interfacing with MongoDB directly, but this means abstracting the way we parse the ss files and bypassing the intermediate json format.

Hopefully we can keep feature paritorty and improve the reload time while still providing a format that works for everyone.

**Comment by mariusursache** [comment]
If you feel that the editor is the only way to be able to work with future
improvements and large amounts of data, I will think of some UI
improvements (and share with you an Axure prototype).

In order for me to do that, can we clarify that these are the fields that
we want in the UI (or, if there are more, please add):

Topics:
* topic name (text input)
* topic keywords (text input)
* system flag (checkbox)
* keep flag (checkbox - from what I understand it's deprecated, but I am
not sure yet).

Gambits
* trigger
* list of replies
* topic

Triggers:
* input filter (autocomplete text input)
* type: default, all questions, WH question etc (droplist)
* user input (text input)

Replies:
* reply filter (autocomplete text input)
* reply (text area)
* dependency to a previous reply in a conversation (currently it is a
separate function, but could stay in the UI, I will find a solution).

**Comment by hipitihop** [comment]
I apologise for my tardy response. I started with learning Superscript using ss files only later I learned about the editor. I found the editor interesting to quickly test tiny experiments but as a dev I must say in comparison I found the ss files allowed me to see more context and obviously anchored by my learning path, I found myself constantly trying to map the editor syntax back to the the rules I had learned via ss files. Now that I have done both only on a superficial level, I can certainly see how ss files are likely more efficient at scale to navigate and write, without the GUI in the way. Opinion so far.

**Comment by mariusursache** [comment]
@hipitihop, I truly agree with that, but I also understand Rob's concern about performance. My intention is to think of an improved UI that allows for the best of both worlds.

@silentrob, maybe it would be good to somehow have a top-level description of your future vision for SS, so that we can contribute to it more. If we want SS to grow, it cannot grow on the shoulders and sweat of only one person. :-)

**Comment by styledondev** [comment]
I am using Superscript as a librar and wanted an fast way to clear and reload the MongoDB instance at will. The admin tool is cool for experimentation, but triggers and replies seem far too important to not have a home in source control/my build process. I modified @ganarajpr's clear script to be a one-stop-shop and removed the intermediary JSON file. It now clears both MongoDB and LevelDB, parses a directory of .ss files, and imports the fresh data back to MongoDB and a LevelDB folder directly before I load my app.

You'll have to change some of the paths if you are running the bot standalone. I also added the following lines to my package.json to allow me to start my app with a fresh bot using the command 'npm run clean'

#### Added to package.json
```
{
    "scripts": {
        "clean": "node cleardb.js && npm start"
     },
    "devDependencies": {
        "bluebird": "^2.9.27",
        "rimraf": "^2.4.1",
        "sfacts": "0.0.12"
    }
}
```

#### cleardb.js
```
///////////////////////////
// Superscript Refresher //
///////////////////////////

var Promise = require('bluebird'),
    superscript = require('superscript'),
    facts = require("sfacts"),
    factSystemDirectory = './systemDB',
    rmdir = Promise.promisify( require('rimraf') ),
    TOPIC_FOLDER = process.env.TOPIC_FOLDER || './topics';


function removeAll (db) {
    /**
     * @param {Object} MongoDB instance
     * @return {Promise} Resolved after listed collections are removed and the fact system directory has been recursively cleared
     */
    var collectionsToRemove = ['users', 'topics', 'replies', 'gambits'];

    return Promise.map(collectionsToRemove, function(collName) {
            var coll = db.collection(collName);
            return coll
                .removeAsync({})
                .then(isClear.bind(collName));
        })
        .then(function() {
            // Delete the old fact system directory
            return rmdir(factSystemDirectory)
        });
};


function isClear () {
    console.log(this + ' is clear');
    return true;
}


function createFresh () {
    /**
     * @return {Promise} Resolves after all data from the Topics folder has been loaded into Mongodb
     */

    // Generate Shared Fact System
    // If not pre-generated, superscript will throw error on initialization
    var factSystem = facts.create('systemDB'),
        parser = require('./node_modules/superscript/lib/parse')(factSystem),
        loadDirectory = Promise.promisify( parser.loadDirectory, parser );

    function importAll (data) {
        /**
         * @param {Object} Parsed data from a .ss file
         * @return {Promise} Resolved when import is complete
         */
        
        // console.log('Importing', data);
        return new Promise(function(resolve, reject) {
            new superscript({factSystem: factSystem}, function(err, bot) {
                if (!err) bot.topicSystem.importerData(data, resolve);
                else reject(err);
            });
        });
    }

    return loadDirectory(TOPIC_FOLDER)
        .then(importAll);
}


// Setup Mongo Client
var MongoClient = Promise.promisifyAll( require('mongodb') ).MongoClient,
    mongoURL = 'mongodb://localhost/superscriptDB';


// DO ALL THE THINGS
MongoClient.connectAsync(mongoURL)
    .then(removeAll)
    .then(createFresh)
    .catch(function(e) {
        console.log(e);
    })
    .then(function(data) {
        console.log('Everything imported');
        return 0;
    }, function(e) {
        console.log('Import error', e);
    })
    .then(process.exit);

```

**Comment by neekolas** [comment]
I am using Superscript as a library and wanted an fast way to clear and reload the MongoDB instance at will. The admin tool is cool for experimentation, but triggers and replies seem far too important to not have a home in source control/my build process. I modified @ganarajpr's clear script to be a one-stop-shop and removed the intermediary JSON file. It now clears both MongoDB and LevelDB, parses a directory of .ss files, and imports the fresh data back to MongoDB and a LevelDB folder directly before I load my app.

You'll have to change some of the paths if you are running the bot standalone. I also added the following lines to my package.json to allow me to start my app with a fresh bot using the command 'npm run clean'

#### Added to package.json
```
{
    "scripts": {
        "clean": "node cleardb.js && npm start"
     },
    "devDependencies": {
        "bluebird": "^2.9.27",
        "rimraf": "^2.4.1",
        "sfacts": "0.0.12"
    }
}
```

#### cleardb.js
```
///////////////////////////
// Superscript Refresher //
///////////////////////////

var Promise = require('bluebird'),
    superscript = require('superscript'),
    facts = require("sfacts"),
    factSystemDirectory = './systemDB',
    rmdir = Promise.promisify( require('rimraf') ),
    TOPIC_FOLDER = process.env.TOPIC_FOLDER || './topics';


function removeAll (db) {
    /**
     * @param {Object} MongoDB instance
     * @return {Promise} Resolved after listed collections are removed and the fact system directory has been recursively cleared
     */
    var collectionsToRemove = ['users', 'topics', 'replies', 'gambits'];

    return Promise.map(collectionsToRemove, function(collName) {
            var coll = db.collection(collName);
            return coll
                .removeAsync({})
                .then(isClear.bind(collName));
        })
        .then(function() {
            // Delete the old fact system directory
            return rmdir(factSystemDirectory)
        });
};


function isClear () {
    console.log(this + ' is clear');
    return true;
}


function createFresh () {
    /**
     * @return {Promise} Resolves after all data from the Topics folder has been loaded into Mongodb
     */

    // Generate Shared Fact System
    // If not pre-generated, superscript will throw error on initialization
    var factSystem = facts.create('systemDB'),
        parser = require('./node_modules/superscript/lib/parse')(factSystem),
        loadDirectory = Promise.promisify( parser.loadDirectory, parser );

    function importAll (data) {
        /**
         * @param {Object} Parsed data from a .ss file
         * @return {Promise} Resolved when import is complete
         */
        
        // console.log('Importing', data);
        return new Promise(function(resolve, reject) {
            new superscript({factSystem: factSystem}, function(err, bot) {
                if (!err) bot.topicSystem.importerData(data, resolve);
                else reject(err);
            });
        });
    }

    return loadDirectory(TOPIC_FOLDER)
        .then(importAll);
}


// Setup Mongo Client
var MongoClient = Promise.promisifyAll( require('mongodb') ).MongoClient,
    mongoURL = 'mongodb://localhost/superscriptDB';


// DO ALL THE THINGS
MongoClient.connectAsync(mongoURL)
    .then(removeAll)
    .then(createFresh)
    .catch(function(e) {
        console.log(e);
    })
    .then(function(data) {
        console.log('Everything imported');
        return 0;
    }, function(e) {
        console.log('Import error', e);
    })
    .then(process.exit);

```

**Comment by silentrob** [comment]
@neekolas If you are intertested, I would happly merge that PR.

**Comment by neekolas** [comment]
Wouldn't be too hard to generalize it so it works with the standalone bot.
I'll put something together tonight.
