### ISSUE TITLE
Question types replies do not work properly (even if triggers are identified correctly).

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript#127]
I have defined four gambits to test question matching:

```
?:WH *
- This is a WH question

?:YN *
- This is a yes/no question

?:TG *
- This is a tag question

?:CH *
- This is a choice question
```

If I ask **Who is Matt Damon?** or **Do you want to eat?** or **Is Mary taller than Tom?**, I always get the first reply, **This is a WH question**, and whatever question I test in the editor, it seems that it matches all the gambits:

![image](https://cloud.githubusercontent.com/assets/867133/8904410/6e2f9dcc-345f-11e5-9077-4e420a6128be.png)

Most likely related to: https://github.com/silentrob/superscript-editor/issues/25

/cc @Laurian

**Comment by silentrob** [comment]
@mariusursache can you confirm if this is an editor issue or a superscript issue. If it is tha editor, lets move it there and close this.

**Comment by mariusursache** [comment]
Editor. Did not try it in the latest commit. I can't write a test but I can definitely write a script to help you replicate stuff. Will do that tomorrow between flights.

**Comment by silentrob** [comment]
This should work fine in SS. If there are issues I will investigate further. I think this is just a bug in the editor.
