### ISSUE TITLE
Capturing replies does not work as expected.

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript#128]
```
+ *1 is taller than *1
- <cap1> is taller than <cap2>
```

The trigger *John is taller than Mark* results in the *John is taller than undefined* reply. If I use instead `<cap1> is taller than <cap3>` it works, meaning that somehow things broke in one of the last releases (used to work properly before).

Using `*~1` or `*(1-1)` works properly.

**Comment by silentrob** [comment]
I think in one case we had an extra space leading, that is now trimmed away too.
