### ISSUE TITLE
Alternates parsing removes all parenthesis from replies

### ISSUE THREAD

**Issue by karovski** [silentrob/superscript#130]
As per title. This makes it impossible to save replies with words in parenthesis due to the way it's parsed.

Method in question: https://github.com/silentrob/superscript/blob/master/lib/processtags.js#L92-L117

I did a workaround for this issue by using an alternate syntax for alternates which uses double parenthesis: `(( alternate1 | alternate2 | ... ))`

The relevant issue and commit are https://github.com/eternime/superscript/issues/2 and https://github.com/eternime/superscript/commit/7b249857c2f9bcb20aa523533ec0adb774830742

Additionally, the original regex removes all whitespaces _after_ the alternates group, whereas the workaround only removes them from within the group.

**Comment by silentrob** [comment]
Okay, so litteral parenthesis were being removed too agressivly. 
Does it make sense to change the reply alt syntax or just escape parens? 
`I like \( this or that \)`

Or if we go to a double parenthesis then we should probably change the alternate syntax on the gambit side too.

Thoughts?

**Comment by karovski** [comment]
I remember trying the escaped approach and I think I had issues with negative lookahead in the regexps, and also the function was getting pretty messy.

Essentially, either is good. I went with double parenthesis because it was a solution to solve an immediate problem.

**Comment by silentrob** [comment]
Oh, this is fixed now too in the follow PR https://github.com/silentrob/superscript/pull/139
