### ISSUE TITLE
Reply cleaning removes quote characters

### ISSUE THREAD

**Issue by karovski** [silentrob/superscript#131]
Due to cleaning rules double and single quotes that have whitespace in front of them are replaced with a single whitespace.

Commas are also removed if they're surrounded by whitespaces.

Examples:
`I do 'want' to "use" quotes`
`I do want' to use" quotes`

`I do ""not" know how to ''use' quotes`
`I do "not" know how to 'use' quotes`

The cleaning is done in https://github.com/silentrob/superscript/blob/master/lib/message.js#L32-L37:

```
var cleanIncomming = function (message) {
  message = message.replace(/\s,\s/g, " ");
  message = message.replace(/\s"\s?/g, " ");
  message = message.replace(/\s'\s?/g, " ");
  return message;
};
```

Semi-related question: Are there still cases when normalizer would yield results that require this cleanup?

**Comment by silentrob** [comment]
I send the reply off to the message factory, but retain the reply string for the client.
