### ISSUE TITLE
Crash on specific initial bot input

### ISSUE THREAD

**Issue by karovski** [silentrob/superscript#132]
If the first ever input is of the form: `__string__` a crash occurs. 

Repro (ES6):
``` 
  new SuperScript( (err, bot) =>{
    if (err) {
      return;
    }
    bot.reply('test', '__something__', (reply) => {
    });
  }); 
```

It appears that a wordnet (node-wordnet) lookup is done in this case where the actual error takes place:

Top output:
```
superscript/node_modules/lemmer/node_modules/node-wordnet/lib/wordnet.js:419
    forms = tokens.map(function(token) {
            ^
ReferenceError: tokens is not defined
```

**Comment by silentrob** [comment]
So, I fixed this here https://github.com/silentrob/lemmer/commit/d718465f03b6e5906cad7dfdf05faaeb7b0b9e45

And will open an issue on the dependancy, to resolve it properly.

**Comment by silentrob** [comment]
okay, turns out it was already fixed in node-wordnet, so now it is double fixed!
