### ISSUE TITLE
"Inception" conversations issues

### ISSUE THREAD

**Issue by mariusursache** [silentrob/superscript#133]
Whenever a conversation is structured on more than one levels, there are a few issues with matching last reply and the order the children gambits are matched.

Example:

```
+ start
- What is your name?

    + [my name is] *1
    % * what is your name *
    - So your first name is <cap1>?

    + [my name is] *1 *1
    % * what is your name *
    - So your first name is <cap1>?

        + ~yes *
        % * so your first name is *
        - That's a nice name.

        + ~no *
        % * so your first name is *
        - I'm a bit confused.
```

Conversation:
1. Bot: What is your name?
2. Me: My name is Marius Ursache
3. Bot: So your first name is Marius?
4. Me: Yes
5. Bot: So your first name is ?

From what I see, when I say **Yes** it matches `[my name is] *1` despite the fact the previous reply is **So your first name is Marius**

Ideally, matching should be done first time on the last reply, then (if no match found), try the reply before last etc. (so go up the last reply tree), right?

Some issues which might be related: #100, #93, #83.

**Comment by silentrob** [comment]
So it appears conversation gambits are being mixed into the main topic and polluting the scope.

**Comment by dcsan** [comment]
I'm not up to date with the syntax, but is the nesting/whitespace in the above example important for the interpreter, or just text formatting for readability?

**Comment by volumetric** [comment]
I have also noticed this behavior.

**Comment by silentrob** [comment]
@dcsan just readability.

**Comment by silentrob** [comment]
So the problem was how we classified previous messages and turned them into conversation. I have relaxed the syntax and it is now case insensitive.

**Comment by silentrob** [comment]
I have verified this cause works too. 
https://github.com/silentrob/superscript/blob/master/test/fixtures/continue/main.ss#L69-L87
