### ISSUE TITLE
how does the logic work?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#137]
I'm not sure if the logic is broken in the editor or I'm doing something wrong. I realize the design is not meant to be deterministic, but i can't seem to get a conversation started.

`random` is the default topic, correct (like Rivescript)?

### 1. **I added a wildcard gambit in the 'random' topic.**

![image](https://cloud.githubusercontent.com/assets/514002/9295453/7c0529fc-4423-11e5-9c31-4bfa1aac8aa7.png)

### 2. tested it out there

![image](https://cloud.githubusercontent.com/assets/514002/9295458/9ad4c928-4423-11e5-97c3-829fbc8c20fc.png)

### 3 double checked matches in the topic screen
![image](https://cloud.githubusercontent.com/assets/514002/9295471/e55bc1a4-4423-11e5-885f-ee1fea3c56e0.png)

### 4 but I still can't matches in the conversation 

![image](https://cloud.githubusercontent.com/assets/514002/9295445/490b80dc-4423-11e5-93e0-935dcdb46e92.png)

other perfect matches will trigger, eg
eg `hello > how are you?`

so i don't think its a "you're in the wrong topic" problem.

Is this not how the system works? I just can't seem to get to grips with the system even after writing tons of bot scripts with Rive.

**Comment by dcsan** [comment]
also tried toggling these two as the 'keep' thing seemed to make the system discard matches last time i tried SS

![image](https://cloud.githubusercontent.com/assets/514002/9295508/260a4968-4425-11e5-9eae-6d51af8f24a8.png)

**Comment by silentrob** [comment]
This is an issue for the Editor. Closing here as wont-fix

**Comment by dcsan** [comment]
Ah, so move the issue to the editor repo?

I understand the editor is now the only way to enter scripts into the system? Or do you still support some method of parsing scripts?

If the top level entry to the system is broken via the editor, then what's the recommended way to start with a script? Perhaps noone else noticed as you aren't creating new scripts atm, rather extending existing ones.

**Comment by silentrob** [comment]
We have taken a step back on that point and supporting scripts still works and is preferred by a large part of the ss community. I have put the editor on ice until superscript is at least 1.0. This should allow us to flush out the remaining pieces on the project while not worring about keeping everything in sync.

**Comment by dcsan** [comment]
ok great! are there docs on how to load up a script and have it be parsed? 
I was looking at the Wiki but couldn't find a real idiots getting started guide...
https://github.com/silentrob/superscript/wiki/Under-the-Hood
and the main site...

**Comment by silentrob** [comment]
We can improve that. There is an included binary called `parse` it is in the bin folder. That will load the scripts into the database and get you going.
