### ISSUE TITLE
Sending multiple Replies for a given trigger

### ISSUE THREAD

**Issue by volumetric** [silentrob/superscript#140]
I want to send multiple replies to a given user query or trigger, in a timely controlled manner. like if a users asks for what are the colors in the rainbow, then i want to send the color names and picture of the colors, in seven different replies. Is this possible to do this with the current system. maybe using the plugin system.

In this case, the system is making a I/O request (getting different images from external resources) which can take time, so the bot will send the first response to the the user, and send subsequent responses, as it fetches the resources (images), in a timely controlled manner.

One way i tried is to use the plugin system, and in the function call for a response, i tried calling the callback function more than once, in the hope that the 2nd response will go over like the first one, but it doesn't seems to work that way.
```
+ aaa
- {keep} ^aaa(bbb)

exports.aaa = function(arg, cb) {
	if (typeof(arg) == "function") {
		cb = arg;
		arg = null;
	}
	cb(null, "reply to aaa. with arg: " + arg);
	cb(null, "AGAIN ==> reply to aaa. with arg: " + arg);
	// setTimeout(function(){
	// 	cb(null, "After 3 sec delay. ===> reply to aaa. with arg: " + arg);
	// }, 3000);
}
```

Here i only get the first response and not the second response.
Is there a way that this can work with multiple call to the callback function, that way i can schedule multiple responses in a timely manner.

Thanks for your help

**Comment by silentrob** [comment]
Okay, this is a great idea, and one that has been on my mind for the past week or so. It is not entirly natural to have symetic conversations, the brain and thought process dosn't work this way.

Have said that it could open the door to creating messy and complex reply threads, but I think that is also natural, and Im in favor of a feature like this. So as you guessed, this is not support at the moment and I appude your attempt to fire the callback twice. 

The actual code that needs to change is probably here - https://github.com/silentrob/superscript/blob/master/index.js#L197-L239

So right now when a message comes into the system we break it down by sentence or phrase and process each message chunk seperartly. For example `My name is Rob. What is your name?` and `My name is Rob, what is your name.` Are both treated as two messages into the system and will already generate 2 replies. However the replies are concatinated back together and sent as one to the user.

So what I think we are looking for here is a way to send a sub-reply with an optional time delay. We could piggy back off of the existing mult-line reply, however the internalls would need to change.
```
+ What are the colors of the rainbow
- Red orange yellow
^ green, blue and umm
^ indigo and violet 
```
```
+ What are the colors of the rainbow
- Red orange yellow
^ {delay=500} green, blue and umm
^ {delay=1000} indigo and violet 
```
Adding a delay flag in ms.
I'm open to other ideas as well.. lets riff on this and add it in.

**Comment by mariusursache** [comment]
We've already developed a delay plugin, but most things are done in the
front-end, this is why we did not contribute it (too specific for our app).
@karovski can offer more details.

**Comment by volumetric** [comment]
@mariusursache have you implemented multiple delayed replies for a given trigger, using a plugin?
if so, Please do share, how you did it.

**Comment by silentrob** [comment]
@volumetric I believe this work was done outside superscript core and up in the client layer. We will find a way to make this happen in the core library. Also we can chat about the internals in slack.

**Comment by volumetric** [comment]
Sure, that would be better.

**Comment by silentrob** [comment]
So this is ready to be tested and played with. I was able to get it to work with the API I suggested above. however the final message back to the end user is still on the client to implement. 

Here is what the payload looks like.
```
{ replyId: 55dc0d34136d3b8783ec208e,
  createdAt: Mon Aug 24 2015 23:37:45 GMT-0700 (PDT),
  string: 'red',
  gambitId: 55dc0d34136d3b8783ec208d,
  topicName: 'random',
  subReplies: 
   [ { delay: '500', string: 'orange' },
     { delay: '500', string: 'yellow' },
     { delay: '500', string: 'green' },
     { delay: '500', string: 'blue' },
     { delay: '500', string: 'and black?' } ] }
```
So now there is a subRelies key with each new message and the delay added.
