### ISSUE TITLE
Erro installing Superscriptjs on dreamhost:

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#144]
Trying to install superscriptjs on dreamhost vps with nodejs and mongodb installed, I receive these errors:
In this hosting I am using php 5.6, NODEJS version is v0.12.0, with mod security enabled:
http://wiki.dreamhost.com/Mod_security
and here the dreamhost instructions about nodejs setup:
http://wiki.dreamhost.com/Passenger

Here my failed installation:

[HOSTNAME]$ npm install --global superscript
npm ERR! tar.unpack untar error /home/anonymousfolder/.npm/superscript/0.9.1/package.tgz
npm ERR! Linux 3.1.9-vs2.3.2.5vs2.3.2.5+
npm ERR! argv "/usr/local/dh/nodejs/bin/node" "/usr/bin/npm" "install" "--global" "superscript"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! path /usr/local/dh/nodejs/lib/node_modules/superscript
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, mkdir '/usr/local/dh/nodejs/lib/node_modules/superscript'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, mkdir '/usr/local/dh/nodejs/lib/node_modules/superscript']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/dh/nodejs/lib/node_modules/superscript',
npm ERR!   fstream_type: 'Directory',
npm ERR!   fstream_path: '/usr/local/dh/nodejs/lib/node_modules/superscript',
npm ERR!   fstream_class: 'DirWriter',
npm ERR!   fstream_stack:
npm ERR!    [ '/usr/local/dh/nodejs/lib/node_modules/npm/node_modules/fstream/lib/dir-writer.js:36:23',
npm ERR!      '/usr/local/dh/nodejs/lib/node_modules/npm/node_modules/mkdirp/index.js:46:53',
npm ERR!      'FSReqWrap.oncomplete (fs.js:99:15)' ] }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/anonymousfolder/anonymousdomain.com/public/npm-debug.log
[HOSTNAME]$

**Comment by silentrob** [comment]
It looks like Dreamhost will not allow you to install it global without using "SUDO" you might have to install it locally without the "--global" flag.

**Comment by Laurian** [comment]
You can also tell `npm` where to install global packages like `NPM_PACKAGES=/somewhere-I-can-write/npm-packages npm install --global superscript` but you will have to provide that env variable again when running it with node.

That also works if you have a package that on `npm install` will try to install a dependency globally (I think I had this issue with superscript in the past), so if your non-global `npm install` does install in `node_modules`, you can force any global installation called in that process to be in the same folder like `NPM_PACKAGES=./node_modules npm install superscript` and you don't have to provide this variable again when running it.

**Comment by matteoraggi** [comment]
Thanks! Adding the sudo users then it workes, Great!
Now I am going to install the web editor of superscriptjs: https://github.com/silentrob/superscript-editor
but what about Mongodb? When and for what I have to configurate it?

**Comment by matteoraggi** [comment]
All right! I installed also the editor:
SuperScript Community Editor.
        Listening at http://0.0.0.0:3000
        Bot Name: testbot

        Switch or create a new bot by starting `BOT=<name> node app.js`

**Comment by dcsan** [comment]
you might want to use a service like Digital Ocean, they have MEAN stack droplets pre-configured. so you won't have to worry about mongo etc.

dreamhost (I used them myself) seems much more old-school shared php hosting...

**Comment by matteoraggi** [comment]
Thanks! Considering that Dreamhost is fully managed instead on Digital Ocean then I have to take care about the security by myself, and many more.. because it is not fully managed, and that is a big task that I skip with Dreamhost... I am also evaluating other webserver with nodejs, that are also free at the start, like: heroku.com, openshift.com, Nodejitsu, Microsoft Azure, Modulus.io.

**Comment by silentrob** [comment]
I didn't realize Nodejitsu was still running after the GoDaddy aquisition. Any platform that dives you access to the VM is all you really need. I use Ec2 and they have a free tier to play with as well.

**Comment by kirsle** [comment]
I used to work at DreamHost, and I recommend Digital Ocean (they're who all my stuff is currently hosted with). You get more options for operating systems with DO (whereas DreamHost is limited to just Debian, and they're probably still on Wheezy)... Digital Ocean gives you full access to the VPS, whereas DreamHost is really built around the idea of managing your system through their control panel. For example, I manually added a lot of users to a DreamHost server via the CLI (`adduser`, etc.) to find out later that my `/etc/passwd` and `/etc/shadow` files got wiped out overnight by DreamHost when their control panel system synced configs down to my server. You can configure a DreamHost VPS to be unmanaged (by creating a sudo user through the control panel first), but that process was pretty unintuitive.

**Comment by silentrob** [comment]
:+1:
