### ISSUE TITLE
How to publish superscriptjs, one time installed?

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#145]
I have installed superscriptjs, and it tell me:
>SuperScript Community Editor.
>Listening at http://0.0.0.0:3000
>Bot Name: testbot
>
> Switch or create a new bot by starting `BOT=<name> node app.js`

What I should do now to publish it into a subfolder of a website?
Because http://0.0.0.0 is not a real website obviously..

**Comment by silentrob** [comment]
The editor is just for authoring and does not provide a production ready client. That exercise is left upto you as there are so many use-cases for chat. Web, slack, irc, skype, twitter etc. I have some barebones clients in the repo you can take a look at.

Happy to help point you in the right direction. Lets use the slack channel for general discussion.

**Comment by matteoraggi** [comment]
Yeah a standard chat system would be great! I just need to do some tests to build a demo, then I will do some design. I love your default chatbot design:
http://superscriptjs.com/img/realtime.png
In this your repo I didn't found anything  about a chat client:
https://github.com/silentrob?tab=repositories
https://github.com/silentrob/repositories

**Comment by matteoraggi** [comment]
Ok I wait in the slack channel, I will just search for a opensource-jquery responsive client.

**Comment by matteoraggi** [comment]
I suppose that this is the demo client that you was writing about : https://github.com/silentrob/superscript-websocket-demo
