### ISSUE TITLE
Skip TTS and Play audio files like many gps navigators do

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#146]
What about if instead to power up superscriptjs with a TTS, I would like to set the audio with 100% audio files (like mp3 for example or 3gp..) ? Or develop a mix of them.. for example if I have the mp3 file associated, I play the mp3, if not, I call the API of the TTS. Suggestions?

**Comment by silentrob** [comment]
So you are looking for a STT (Speach to text) interface to power superscript? I think problem is already solved or can be layerted on by using another API or service to do that. Either way, it is out of scope for what we are trying to do.

**Comment by matteoraggi** [comment]
Not only STT,  also  TTS, yes you are right.
