### ISSUE TITLE
Website documentation is broken

### ISSUE THREAD

**Issue by mfornasa** [silentrob/superscript#150]
http://superscriptjs.com/documentation/scripting

![screen shot 2015-09-21 at 16 57 15](https://cloud.githubusercontent.com/assets/280285/9995327/d618fdb8-6081-11e5-8809-c7105c39254c.png)

**Comment by mariusursache** [comment]
The documentation has moved to the wiki in this repository.

**Comment by mfornasa** [comment]
Ok. You should remove the broken one in the website.

**Comment by mariusursache** [comment]
@silentrob Can you redirect from the superscriptjs.com site to this wiki for documentation? This way we avoid future confusion and duplication.

**Comment by silentrob** [comment]
Fixed and deployed.
