### ISSUE TITLE
Guided questions

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#157]
Instead to use the superscriptjs engine to answer to the human questions, why not use superscript to collect data from humans? For exampe:
- How many girlfriends you got in your life?
+ 13
- Well! Better then nothing! And how many times you got marriage?
+ Just one
- Good! I am happy for you! Are you still married?
+ Yes I am married
- Are you marriedi n Europe or where?
+ Europe
* In the old continent very well, I ma happy for you!

**Comment by mariusursache** [comment]
@matteoraggi Of course it can be used like this. It's a dialogue manager and works both ways. We are using scenarios like you described in our project.
Please discuss these things on Slack, as Github issues are mostly for bugs, enhancements or features. :-)

**Comment by matteoraggi** [comment]
Thanks a lot! So just to end this conversation, my question is: how to make superscriptjs to start the conversation instead to wait that the human speak to him?

**Comment by mariusursache** [comment]
Send to the bot a trigger such as `__open__` when the bot initializes (but 
not
visible in the UI), and then treat the case in a SS gambit that fires a bot
reply to that trigger.
