### ISSUE TITLE
Installing superscript on koding.com VM

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#166]
If I update with apt upgrade nodejs and mongodb, then when I run the npm install 
I receive the following errors:

gyp http 200 http://nodejs.org/dist/v0.10.26/node-v0.10.26.tar.gz
gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Linux 3.13.0-29-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/droidary/superscript-editor/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

And IF then I launch it, I receive this error:
> leveldown@0.10.5 install /home/droidary/superscript-editor/node_modules/superscript/node_modules/sfacts/node_modules/leveldown
> node-gyp rebuild
 
chdir(): No such file or directory

If instead I don't update, I receive a mongodb error, that I will publish soonest as possible.

**Comment by karovski** [comment]
Not sure what the VMs run on but you need to have the `make` build tool installed in order for some of the modules to build. Debian based: `apt-get install build-essential`

Not sure if you might need to install `g++`.

**Comment by matteoraggi** [comment]
Ok done thanks! mongodb was using 3.5 gb of the total of 3gb of the free account, and in the documentation they explain how to save space.
