### ISSUE TITLE
Update docs to include topicRedirect and respond

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#172]
Replies can have a `respond()` function to redirect and search in another topic, including hidden topics.
Replies can have a `topicRedirect()` function to redirect to a certain gambit in another topic
Repleis can have an inline redirect (already documented)
Replies can have a custom functions as well as filter functions.

All of these things can be nested in any order to create even more compled rules and conversations.
For example, A reply can redirect to another gambit which calls a function that changes the topic and searches for another topic to find a matching gambit.

**Comment by mariusursache** [comment]
Done.
