### ISSUE TITLE
Topic state confusion

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#173]
With the following code
```
+ name
- {keep} ^respond(set_name)

> topic:keep set_name
  + *
  - What is your first name?

  + *~5
  % * is your first name?
  - ^save(firstName, <cap>) Ok <cap>, what is your last name?

  + *~5
  % * what is your last name?
  - ^save(lastName, <cap>) Thanks, ^get(firstName) ^get(lastName)! {topic=random}
< topic
```
I'd expect to enter and stay in 'set_name' throughout the sequence. 

However when responding to 'what is your name?' the bot does not a find a response and results in a null message and undefined topic (currentTopic and pendingTopic are both Null for the user).

**Comment by Lewwwk** [comment]
It's seems that the use of any function within a topic returns an empty message and null topics. Could this be related to the 0.10.0 update?

**Comment by silentrob** [comment]
Yes I think so. I will push a fix today.

**Comment by Lewwwk** [comment]
Also, in case it's helpful, seems that inputs are getting matched against system topics even if not in the system topic.

**Comment by silentrob** [comment]
So looking at the logs here...
```
  GetReply Topics to check +805ms [ { id: 5643917a61880afbb7ea3959, type: 'REPLY' },
  { name: 'random', type: 'TOPIC', id: 5643916261880afbb7ea38d1 },
  { id: 5643917a61880afbb7ea395a,
    name: 'fish',
    system: false,
    type: 'TOPIC' },
  { id: 5643917a61880afbb7ea395f,
    name: 'rainbow',
    system: false,
    type: 'TOPIC' },
  { id: 5643917b61880afbb7ea3964,
    name: 'set_name',
    system: false,
    type: 'TOPIC' },
  { id: 5643917b61880afbb7ea3967,
    name: 'suba',
    system: false,
    type: 'TOPIC' } ]
  mquery findOne +3ms { _id: 5643917a61880afbb7ea3959 } { fields: undefined }
  GetReply Conversation Reply Thread +1ms { reply: '^respond(set_name)',
  parent: '5643917961880afbb7ea3958',
  _id: 5643917a61880afbb7ea3959,
  __v: 0,
  gambits: [],
  filter: '',
  keep: true,
  id: 'ZMaY1J8u' }
```
It seems like we are trying to do the right thing, first looking at the REPLY, before the topics, but in this case the reply ID is the reply of the `^respond()` and not the actual reply id inside the set_name topic, so when we look up the parent_id, we get the random topic.

**Comment by silentrob** [comment]
I would also like to see the set_name topic to be higher in the list, but that may be a seperate issue.

**Comment by silentrob** [comment]
This should now be fixed and is in master

**Comment by Lewwwk** [comment]
It runs correctly for me with my only remain question being:  

After it provides the last reply ```^save(lastName, <cap>) Thanks, ^get(firstName) ^get(lastName)! {topic=random}```

Shouldn't ''user.currentTopic == random```? Currently it stays at ```set_name```?
