### ISSUE TITLE
{keep} shows in reply if there is also a filter in the reply

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#175]
With this ss...
```
+ keep with filter test
- {keep}{^hasName(true)} result
```
I get this result...
```
You> keep with filter test

Bot> {keep} result
You> 
```

The expected result wouldn't have {keep} in the reply.
```
Bot> result
```

**Comment by silentrob** [comment]
This is actually in the parser lib. I wonder what happens when you have the the filter function furst.
`- {^hasName(true)}{keep} result`

**Comment by silentrob** [comment]
I stand corrected, this is in superscript, not the parser.. that should probably change at some point.

**Comment by silentrob** [comment]
This is in `0.10.3`

**Comment by Lewwwk** [comment]
w00t!
