### ISSUE TITLE
@ prevents wildcard capture

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#176]
While attempting to save email addresses, I discovered the following.

Using this script:
```
+ save email *~5
- {keep} saving email <cap> ^save(email,<cap>)
```

We can see the following results:
```
You> save email one two three

Bot> saving email one two three  //one two three is saved as expected
You> save email one. two three

Bot> saving email one  //message broken into two sentences, one is still captured, as expected.
You> save email one@two.three

Bot>                     //with @symbol, nothing is captured 
You> save email one@two

Bot>                     //with @symbol, nothing is captured
You> save email one @ two

Bot>                     //with @ symbol, nothing is captured
You> save email one.two three

Bot> saving email one //message broken into two sentences, one is still captured
You>            
```

**Comment by Lewwwk** [comment]
As a side note, that the message gets broken into two after a period(even if no trailing space after period) is probably the right thing. still sorting out the implications for capturing email addresses in that situation. in the interim have been using ```+ trigger *``` then processing against ```this.message.original```.  Given that any email address will necessarily be split into two messages, i can see this leading to unexpected results.

**Comment by mariusursache** [comment]
Why don't you try processing the input with a function then create a filter 
that
also extracts the email as a capture?
The current parser is based on RegEx so there are a lot of characters that 
are
escapes in conversations, therefore gambit rules/wildcards can't handle all
these situations. If they did you would need a syntax such as `(*)@(*).(*)`
which does not work now because the period is escapes. So... Functions. :-)
Hint: look in the wiki at using filter functions in triggers (not() 
function)

**Comment by Lewwwk** [comment]
I am currently doing something similar - i think. https://gist.github.com/Lewwwk/feca922f5c68175c4bf4

**Comment by Lewwwk** [comment]
Clarifying - it's not that the input isn't being captured, is that it's returning an empty reply. So this means the only way to process an input that has a @ in it is by using a * wildcard (which will accept the message and parse it into two sentences because of the .tld).

**Comment by silentrob** [comment]
@Lewwwk I want to follow up and see if this behavior is fixed with the change to the lexor splitting sentences now.

**Comment by Lewwwk** [comment]
Unfortunately not. Parsing returns empty message when an ```@``` symbol is included in a wildcard capture. (running ss 0.10.5)

**Comment by silentrob** [comment]
I believe this works as expected in 0.10.7. The change was in here - https://github.com/silentrob/superscript/blob/master/package.json#L57

You might need to blow out your node_modules and re-run `npm install`
