### ISSUE TITLE
installing locally on ubuntu 15.10 I receive errors from some libraries

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#183]
In file included from ../src/batch.cc:5:0:
../../nan/nan.h:261:25: error: redefinition of ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Local<T>)’
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Local<T> val) {
                         ^
../../nan/nan.h:256:25: note: ‘template<class T> v8::Local<T> _NanEnsureLocal(v8::Handle<T>)’ previously declared here
 NAN_INLINE v8::Local<T> _NanEnsureLocal(v8::Handle<T> val) {
                         ^
../../nan/nan.h:661:13: error: ‘node::smalloc’ has not been declared
     , node::smalloc::FreeCallback callback
             ^
../../nan/nan.h:661:35: error: expected ‘,’ or ‘...’ before ‘callback’
     , node::smalloc::FreeCallback callback
                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(char*, size_t, int)’:
../../nan/nan.h:665:50: error: ‘callback’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                  ^
../../nan/nan.h:665:60: error: ‘hint’ was not declared in this scope
         v8::Isolate::GetCurrent(), data, length, callback, hint);
                                                            ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(const char*, uint32_t)’:
../../nan/nan.h:672:67: error: no matching function for call to ‘New(v8::Isolate*, const char*&, uint32_t&)’
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../src/batch.cc:2:0:
/home/ubuntu/test/superscript-editor/node_modules/leveldown/.node-gyp/5.1.0/include/node/node_buffer.h:31:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ubuntu/test/superscript-editor/node_modules/leveldown/.node-gyp/5.1.0/include/node/node_buffer.h:31:40: note:   conversion of argument 3 would be ill-formed:
In file included from ../src/batch.cc:5:0:
../../nan/nan.h:672:67: error: invalid conversion from ‘uint32_t {aka unsigned int}’ to ‘node::encoding’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
In file included from ../src/batch.cc:2:0:
/home/ubuntu/test/superscript-editor/node_modules/leveldown/.node-gyp/5.1.0/include/node/node_buffer.h:43:40: note: candidate: v8::MaybeLocal<v8::Object> node::Buffer::New(v8::Isolate*, char*, size_t) <near match>
 NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                        ^
/home/ubuntu/test/superscript-editor/node_modules/leveldown/.node-gyp/5.1.0/include/node/node_buffer.h:43:40: note:   conversion of argument 2 would be ill-formed:
In file included from ../src/batch.cc:5:0:
../../nan/nan.h:672:67: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
                                                                   ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanNewBufferHandle(uint32_t)’:
../../nan/nan.h:676:29: error: could not convert ‘node::Buffer::New(v8::Isolate::GetCurrent(), ((size_t)size))’ from ‘v8::MaybeLocal<v8::Object>’ to ‘v8::Local<v8::Object>’
     return node::Buffer::New(v8::Isolate::GetCurrent(), size);
                             ^
../../nan/nan.h: In function ‘v8::Local<v8::Object> NanBufferUse(char*, uint32_t)’:
../../nan/nan.h:683:12: error: ‘Use’ is not a member of ‘node::Buffer’
     return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
            ^

**Comment by matteoraggi** [comment]
also with nodejs 5.x I can't install, it answer: error on the node...

**Comment by silentrob** [comment]
Yes, node 5.x is a non-starter right now, there are efforts underway to make it work, but you will need to stick to node 0.12.x right now.

**Comment by matteoraggi** [comment]
with node 0.12 and mongo 2.6.9 don't works too. Are there soem suggested versions for mongodb and are there some suggested versions of ubuntu/debian?

**Comment by matteoraggi** [comment]
To me it look to be all right, but the problem is that the new setup is missing to install one database, and it not start because it not find a table, please patch it and let me know:
> node app

/home/ubuntu/ss/superscript-editor/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:299
          throw err;
                ^
Error: Cannot find module 'superscript/lib/wordnet'

**Comment by Lewwwk** [comment]
@matteoraggi you could try what @econohead suggested in #190.  Also as @silentrob said - editor is not maintained. You should have better results installing superscript directly.

**Comment by Lewwwk** [comment]
If you have success with straight superscript, you could then also close #181 and #182 if they are related to the editor version.

**Comment by matteoraggi** [comment]
I have patched the problem moving some files that the setup was not doing by itself.
