### ISSUE TITLE
which version of nodejs, mongodb is needed over ubuntu 14.03? or which linux distro?

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#185]
on ubuntu 14.03 apt-upgrade nodejs e mongodb 
I receive then this error:
weird error 127

**Comment by silentrob** [comment]
SuperScript is not tested actively on unix, but I have no reason to believe it won't work. YMMV. 
Node 0.12.x latest Stable Mongo. 

If you run into any bugs, please report them so we can work though it. PR's are also encouraged and welcome.
