### ISSUE TITLE
node 0.12.8 python 2.7 mdb 3.2 ubuntu 14.03: ss don't works

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#188]
node 0.12.8 python 2.7 mongodb 3.2 ubuntu 14.03 doesn't works the installation of superscript last version.

**Comment by silentrob** [comment]
This is not very helpful, and you have created 5 issues that are almost identical. Perhaps you should have a conversation in the slack channel to help walk though the issues you are seeing. I would also recommend setting up superscript locally (preferably on a mac) to start then try it again on ubuntu.
