### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#189]
What about authentication with ss? Which is a good way to make the users to authenticate and permit ss to know with who is chatting with?

**Comment by Lewwwk** [comment]
The bot already recognizes users. In the telnet case based on socket ip. I would envision any further level of authentication management handled client side as opposed to within the bot engine itself.

**Comment by matteoraggi** [comment]
Any suggestionsabout saving the users answers in the database?

**Comment by Lewwwk** [comment]
Here's the current documentation: https://github.com/silentrob/superscript/wiki/Knowledge#user-knowledge
