### ISSUE TITLE
A new failed setup test 

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#190]
With Mongodb 3.x is all working well, apart this error making ss not usable (I will try to use mongodb 2.8 then):
/home/ubuntu/superscript-editor/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:299
          throw err;
                ^
Error: Cannot find module 'superscript/lib/wordnet'

**Comment by Lewwwk** [comment]
What version of superscript are you using? Doesn't sound like a mongo issue.

**Comment by econohead** [comment]
Look in 'superscript/lib/...’ - I don’t think that file is there. I seem to recall it installs as wndb.js


To get the editor working, just change the name to wordnet.js


—

**Comment by silentrob** [comment]
It is also worth noting that the editor has not been maintained or worked on in several months. precede with caution, and expect issues.
