### ISSUE TITLE
Without the ss editor: where is the text file to edit to configure the bot?

### ISSUE THREAD

**Issue by matteoraggi** [silentrob/superscript#191]
Choosing to not use the superscript editor, then where I can find the file to edit to configurate the bot?

**Comment by matteoraggi** [comment]
I received the answer in chat, thanks!
Once installed, edit “main.ss”. It will be located at /“yourInstallDir”/“yourClient”/topics/main.ss

**Comment by Lewwwk** [comment]
@matteoraggi if you have successfully installed can you then close #181 #182 and #183?
