### ISSUE TITLE
error with npm install

### ISSUE THREAD

**Issue by rayearl** [silentrob/superscript#197]
npm WARN EPACKAGEJSON superscript-editor@0.1.7 No repository field.
npm WARN EPACKAGEJSON superscript-editor@0.1.7 No license field.
npm ERR! Linux 3.13.0-48-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! leveldown@0.10.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the leveldown@0.10.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

[npm-debug.txt](https://github.com/silentrob/superscript/files/54924/npm-debug.txt)

**Comment by LovelyHorse** [comment]
Same issue here!

**Comment by silentrob** [comment]
This is related to the editor which is not maintained anymore. Please switch to using superscript via the parse command.
