### ISSUE TITLE
Conditionals

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#2]
Add conditionals into replies and triggers.

**Comment by dcsan** [comment]
just so I understand, 

```
+ * my name is <name>
- {^hasName(false)} ^save(name,<cap1>) Nice to meet you, <cap1>.
- {^hasName(true)} I know, you already told me your name.
```

so this is calling javascript for a conditional at the beginning of the line which resolves to:

```
{true} reply for true
{false} reply for false
```

normally a JS method is called with `^method()` but in the case where you want a conditional just wrap that inside curly brackets?

**Comment by silentrob** [comment]
So ^hasName() or ^method() are calling a plugin function, and you can pass data into the function. Here is the plugin for the example above https://github.com/silentrob/superscript/blob/master/plugins/reason.js#L8-L17

2 key differences,
{} gets completely removed from the reply, where a normal plugin function results get pushed into the reply stream.
and the filter function wants a boolean value back and not a string.

Im open to riffing on this if you think It could be easier to grok or better in some way.

**Comment by dcsan** [comment]
thanks for the reply. 

> the filter function wants a boolean value 

the filter function is what runs over the possible reply options? ie prefixed per line with `-` ?
eager to try it out but have some other deadlines atm, so just drive-by commenting :)

**Comment by silentrob** [comment]
No problem.
So yes, replies are noted by either '-' or '?' 
'-' can be anything statement, question, command etc.
'?' is only a question and can be further modified with a question type or subquestion type.
functions (both normal plugins or filter functions all look the same, and start with a carrot, followed by parentheses ie: ^somefunction() or ^somefunction(arg1, arg2)
{} are used for things like redirects and filter functions, the results are typically don't make it back into the output stream and get stripped off.

If any of this seems unclear let me know and Ill update the docs.
