### ISSUE TITLE
how much RIVE script is supported?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#20]
I understand this is based off a fork of RIVE script, but I'm wondering what features you support.
for example are variables supported?
https://github.com/dcsan/rivescript-js/blob/master/eg/brain/clients.rive

I tried this:

```
! var name = Suzie

+ hi *
- hi! my name is <bot name>


# output
You> hi 

Bot> hi! my name is <bot name>

```

I don't know rivescript but it would help before i debug to know if this is expected.
I did look in the fixtures but couldn't see any examples of variables.

also this syntax for "learning things"
http://www.rivescript.com/docs/Tutorial.html#learning_things

update: as in #19  it seems there are some syntax differences, so maybe i just need to know what those are.

also if there were any example .ss files that would greatly help to see what can be done!

RIVEscript refs
- https://www.kirsle.net/rivescript
- JS port https://github.com/kirsle/rivescript-js
- JS 'brain' examples: https://github.com/kirsle/rivescript-js/tree/master/eg/brain
- Rivescript tutorial: http://www.rivescript.com/docs/Tutorial.html#name
- RIVE vs AIML http://www.rivescript.com/aiml
- RIVE test suite https://github.com/kirsle/rivescript-js/blob/master/eg/testsuite.rive

**Comment by dcsan** [comment]
quick follow up - so you're using the Rivescript code as is, so pretty much all the stuff listed here should work, at a minimum?

http://www.rivescript.com/docs/tutorial

or did you rewrite big chunks? I'm just wondering if I should get hacking with Rivescript while some of the bugs in the topics etc are worked out.

**Comment by silentrob** [comment]
It is completely re-written. Some of the ideas have been carried over. Read the docs on superscriptjs.com to get a better idea.
