### ISSUE TITLE
Passing temporal data forward within the script

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#207]
```
+ (*) = (*)
- ^setTerm(<cap1>,<cap2>)
	+ ~yes *~3
	% ^setTerm(<cap1>,<cap2>)
	- ^process(<p1cap1>,<p1cap2>)
```

Where pN = Previous Captured input going back in the message history.
The workaround for this now is to store the data (serialized) in `this.user.slot1` and thaw it in `process()`

**Comment by silentrob** [comment]
So this has now landed in "nightly" it allows you to reference and star variable captured in the last 15 messages using <pXcapX> where PX is the Previous index starting at 1 and capX is the star offset again starting at 1.

**Comment by Lewwwk** [comment]
Couple questions here:
- are * wildcards now getting captured? 
- with PX, if it is p1cap1, will that only look for it in the most recent reply, or does it look through all previous 15?
