### ISSUE TITLE
Getting raw input for split messages.

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#210]
In some cases it would be helpful to have the bot not split sentences.  

In particular, sentence splitting makes it difficult to work with raw user input - as the split messages carry a the entire original message in the properties and not the original version of the split chunk. 

Some possible solutions:
- adding a property like originalChunk to the message object that provided the original user input for that message chunk
- enabling a global option to turn off sentence splitting.

**Comment by Lewwwk** [comment]
Correcting above from rawChunk - originalChunk is actually what would be preferred for the purpose of working with original user input.

**Comment by silentrob** [comment]
I have added a global option to disable message chunking. You need to pass an option into the superscript constructor called `chunking` with `false` to disable it.

ie:
```
new superscript({chunking:false /* other options */ }, function(err, bot) {
...
}); 
```
