### ISSUE TITLE
Forced subreply can affect conversation flow

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#213]
I am trying to build a simple topic that captures user input using a custom function. Because a function always returns a subreply, and that subreply currently forces another reply lookup, there can be unintended conversation flows. 

```
> topic:system:keep capture
    + done
    - Thanks for your answer. {topic=random}

    + *
    - ^collectOriginalInput()   //custom function that collects the original input completely.
< topic
```

Hitting the * trigger, the custom function forces a check on the subreply and then matches against the global catchall outside this function, breaking the flow.

While not workable for the conversation flow I'm trying to achieve, in testing I did notice that if I include some reply text in the catchall, it seems to operate as expected, providing the reply, and staying in the topic.

```
+ *
- ^colelctOriginalInput() collecting original input.
```

Similarly if there is no function in the catchall reply, it works as expected.

```
+ *
- collecting original input.
```

In my digging, I thought this issue might be related to this comment:
https://github.com/silentrob/superscript/blob/master/lib/reply/customFunction.js#L33

**Comment by silentrob** [comment]
I believe this was solved by adding a new feature to force continue or break from custom functions.
