### ISSUE TITLE
Front end wildcard capture with chunking turned off

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#214]
When chunking == false, this type of match doesn't work on a multi-sentence input.
```
+ (*) capture
- Capturing <cap>
```
An input of: one two three capture
Results in: one two three

An input of: one. two. three. capture.
Skips the trigger.

This would be normal behaviour, with chunking == true, but not the desired behaviour when chunking == false.  Would be great if the chunking flag could also affect the matching.

**Comment by silentrob** [comment]
So the fix here was to remove the periods, so in your second example it now matches, but the result is `Capturing one two three` If you want the result to be `Capturing one. two. three.` reopen this ticket and I will expand the captured regex in ss-parser.

**Comment by Lewwwk** [comment]
It would ideal if it did capture the periods when not chunking. Not sure if that is better left though to future 'starOriginal'  functionality though.
