### ISSUE TITLE
0.10.21 ^topicRedirect not found

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#227]
In testing the 0.10.21 the following script:

```
> pre
  + ^testState(null) *
  - ^trackEvent(new)^topicRedirect(__onboarding__, __welcome__)
< pre
```
failed with:
> Reply:customFunction Custom Function not-found +7ms topicRedirect

Leaves user with `currentTopic: __pre__`.

**Comment by Lewwwk** [comment]
Have tried a number of combinations of functions. In all those cases, the second one ends up not found.

**Comment by silentrob** [comment]
Ah! I know what the problem is. Thanks for catching this.
