### ISSUE TITLE
0.10.17 colon will not match against variable length wildcard

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#228]
When an input contains `:` it does not seem to match against a variable length wildcard such as`*(2-99)`. 

It will however match against `*`.

Possibly related to #224. Both related to the same kind of wildcard but have different results (this skips the match while #224 hangs the bot).

**Comment by silentrob** [comment]
This is fixed now here https://github.com/silentrob/ss-parser/commit/dbe08cd53a6b2a27b49fd6f1d46af92fe13696ef
