### ISSUE TITLE
multiple copies of the output?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#23]
for some reason I am seeing many duplications of the output:

```
+ hi
- how are you? {redirect=greeting}

+ greeting
- let's get started! {topic=opening}

```
----
```
You> hi

Bot> how are you? {redirect=greeting}
You> 
Bot> how are you? {redirect=greeting}
You> 
Bot> how are you? {redirect=greeting}
You> 
Bot> how are you? {redirect=greeting}
```

FWIW these are the scripts i'm using
https://github.com/dcsan/superscript/tree/master/data

**Comment by silentrob** [comment]
I have disabled the * command for the moment and will bring in back in the next version with a little more thought put into it.
