### ISSUE TITLE
scope creep, user, message and messageScope all leak

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#239]
As per the title

**Comment by Lewwwk** [comment]
wow - nice catch. How was it showing up/what was it impacting?

**Comment by silentrob** [comment]
Anytime a plugin was being called and you used `this.message` `this.user` the user and message may not have belonged to the user and message in question.

**Comment by Lewwwk** [comment]
Very interesting. I bet I've see the result of that - including maybe that issue yesterday.  Will be in next release?






On Sat, Jan 23, 2016 at 9:21 AM -0800, "Rob Ellis" <notifications@github.com> wrote:












Anytime a plugin was being called and you used this.message this.user the user and message may not have belonged to the user and message in question.

**Comment by silentrob** [comment]
Yes, I have a fix complete and will push it shortly.
