### ISSUE TITLE
breakBit doesn't stop reply processing inside a ^topicRedirect()

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#240]
I occasionally want to return empty replies which requires me to use a breakbit so the catchall doesn't take over. If, however, I try to do return an empty reply in a ^topicRedirect() the breakBit doesn't stop the search for a reply.

```
+ test empty
- {keep}^topicRedirect(test, __empty__)

+ test something
- {keep}^topicRedirect(test, __something__)

> topic:keep test
    + __empty__
    - ^returnEmpty(){topic=random}

    + __something__
    - Something{topic=random}

    + *
    - Topic catchall{topic=random}
< topic

+ *
- {keep}Random catchall
```

with the following plugin

```
exports.returnEmpty = function(cb) {
    cb (null, '', true);
}
```

An input of
> test empty

results in
> Random catchall

when the intention is to have an empty reply.

**Comment by silentrob** [comment]
Good catch I was able to reproduce and fix this. It is in 0.11.5
