### ISSUE TITLE
Clarify usage of @ in complex conversations

### ISSUE THREAD

**Issue by bags307** [silentrob/superscript#242]
Can someone please clarify the usage of "{@conversation}" in the complex conversation example in the docs?  

In the example - are they having to say "conversation" as the gambit? 

If I have a response like
` + his name is <name1>
- ok, so his name is <name1>
  
   + ~yes

   % ok, so his name is <name1>
   - Great!

   + ~no

   % ok, so his name is <name1>

   - Sorry about that {@ok, so his name is <name1>} `

or am i doing this wrong?

**Comment by dcsan** [comment]
you should format text with ```
I'm not sure about superscript but Rivescript (which it was once based on) uses @ for arrays.

https://www.rivescript.com/docs/tutorial

    ! array colors = red blue green yellow

Now, you can refer to this array by name in your triggers. Here are a couple examples you can use (you can use arrays in as many triggers as you want):

    + what color is my (@colors) *

**Comment by silentrob** [comment]
Replies can have `{}` Everything between `{` and `}` are removed from the final reply. The `@` is a redirect to another trigger. Three are a few other uses with `{...}` too. They modify how the matching engine works, or conversation state.

**Comment by dcsan** [comment]
oops you mean as per this example:
https://github.com/silentrob/superscript/wiki/Conversations#complex-conversations

the {@something} is like firing a trigger, but acts more like an include.
eg:

```

  + start
  - hello!

  + two
  - {@start}

```

so if the user types `two' then the two trigger will get caught, but the response will be the same as if he typed `start`. 

these docs make it clearer:
https://github.com/silentrob/superscript/wiki/Replies#redirecting-__reply__

at least in rivescript you can also add parameters on, so something like this:

```
+ hello *
- hello <cap>

+ test *
- {hello <cap>}
```

if you type `test foo` it will pass the foo to the hello trigger.

not sure if that's supported in SS.

**Comment by bags307** [comment]
ok. I think I'm understanding.
but if my trigger is 
```
+ I like cheese
- me too

+ I like milk
- {@I like cheese}
```

Is that correct?

**Comment by espinchi** [comment]
@bags307, I would think this last snippet should work. But I've been surprised to see that this is what happens:

This doesn't work:

> You> I like cheese
> Bot> me too!
> 
> You> I like milk
> Bot> 

This does, though. I have no idea why!

> You> I like milk
> Bot> me too!
> 
> You> I like cheese
> Bot> me too!

In any case, I would rather refactor it to have this:

```
+ I like cheese
- {@__love_something__}

+ I like milk
- {@__love_something__}

+ __love_something__
- me too
```

Which happens to work fine in either order.

**Note: ** I started exploring Superscript out of curiosity two days ago, so I'm not exactly qualified to provide authoritative answers.

**Comment by Lewwwk** [comment]
That's how I use - snake casing. Keep in mind also, that replies that aren't flagged {keep} get exhausted... so that the bot is less likely to repeat itself.
