### ISSUE TITLE
Input type catches any input

### ISSUE THREAD

**Issue by espinchi** [silentrob/superscript#246]
Here's my main.ss:

```
+ vacation
- {keep} go to hawaii

+:ENTY:animal *
- {keep} talking about animals

+:NUM:date *
- {keep} talking about dates
```

Here's a conversation:

> You> hello
> Bot> talking about animals
> 
> You> foo bar
> Bot> talking about animals
> 
> You> vacation
> Bot> talking about animals
> 
> You> next Friday
> Bot> talking about animals

**Comment by silentrob** [comment]
So right now the Answer types only work in conjunction with a question type.
```
?:WH:ENTY:animal *
- {keep} talking about animals

?:WH:NUM:date *
- {keep} talking about dates
```
Which means that you can not have a statement in with the desired answer type filtered out (or in)

Looking at both "next Friday" and "talking about animals" the message object does not classify either.
```
  qtype: '',
  qSubType: '',
```
The first step is to see what is happening here - https://github.com/silentrob/qtypes

**Comment by espinchi** [comment]
I see. Then perhaps the bug report should go for the related documentation in the wiki :), since it's that constraint is not necessarily obvious.

I found another way of achieving this (using filters to classify the input myself in a custom function). So, I'll leave this open, but it's up to you if you want to close it.

**Comment by silentrob** [comment]
Agreed. I will update the doc and create a separate issue to find a better way to classify all utterance types.
