### ISSUE TITLE
topic switching works?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#249]
I have a short script that should topic switch.
I get the response before the topic switches, but then the following response doesn't fire, a trigger from a completely different topic gets caught.
I don't think this is related to the {keep} thing since the other (wrong) topic is fired multiple times

script/project is here:

switch to the `grammar` topic
https://github.com/dcsan/ssbot/blob/master/dabot/topics/main.ss#L61

but `start` trigger replies from `movies`

```
> topic:system:keep shared

	+ movies
	- lets talk movies
	^ {topic=movies}{@start}

	+ grammar
	- to grammar
	^ {topic=grammar}{@start}

	+ ~sport
	- lets talk about sports!
	^ {topic=sport}{@start}

	+ new
	- this is new

< topic


> topic sport

	+ start
	- do you like sports?

< topic


> topic random inherits shared

	+ ~emohello [*~2]
	- Hi!
	- Hi, how are you?
	- How are you?
	- Hello
	- Howdy
	- Ola

	+ status
	- topic is ^get(topicName)

< topic



> topic movies inherits shared

	+ start
	- do you like movies?

	+ ~yes
	- thats good to hear

	+ ~no
	- oh, why not?

< topic



> topic grammar inherits shared

	+ start
	- lets talk grammar!

	+ i was <verb>
	- oh, you were <cap>?

< topic
```

```
Hello ::1:60606! Type /quit to disconnect.

You> football

Bot> 
You> start

Bot> do you like movies?
You> start

Bot> do you like movies?
You> start

Bot> do you like movies?
You> new

## note - so not sure why this keeps firing, I thought the `keep` rule would mean it would pick another something at random?

Bot> this is new
You> grammar

Bot> to grammar

## ok, so we get the response saying going to grammar topic

You> start

## but we're still in 'movies'?

Bot> do you like movies?
You> start

Bot> do you like movies?
You> start

Bot> do you like movies?
You> grammar 

Bot> to grammar
You> start

Bot> lets talk grammar!

```

**Comment by dcsan** [comment]
additionally `football` did not seem to match the `+ ~sport` trigger.

**Comment by dcsan** [comment]
is my use of 

`> topic:system:keep shared`

correct? [taken from this example](https://github.com/silentrob/superscript/wiki/Topics#creating-a-new-topic)

the triggers `movies` and `grammar` do seem to be always available, so `topic:keep`

**Comment by silentrob** [comment]
I'm not sure what you WANT it to do, but every part of that demobot is incorrect.  The example in the docs is right. There is no concept of inherit or shared.. Im don't know where that came from or why you think that would work. Please read the docs.

**Comment by dcsan** [comment]
shared is just a topic name for the navigation functions i want to always be available. 

i removed the `inherits`

```
You> grammar

Bot> to grammar
You> start

Bot> do you like sports?
You> 
```

**Comment by dcsan** [comment]
sometimes it works, sometimes it doesn't. 

```
You> grammar

Bot> to grammar
You> start

Bot> lets talk grammar!
You> sport

Bot> 
You> start 

Bot> lets talk grammar!
You> movies

Bot> lets talk movies
You> start

Bot> do you like sports?
You> 
```

I guess this is [by design?](https://github.com/silentrob/superscript/wiki/Topics#topic-flow)

> Hey, I got bored and changed the topic to something else, maybe

**Comment by Lewwwk** [comment]
@dcsan it works correctly as per docs. It is different than rivescript.

**Comment by dcsan** [comment]
so the above is not a bug? its meant to pick triggers at random from any topic in the system? what's the function of topics then?

I'm surmising there is maybe some weighting algorithm between global not-used triggers vs triggers in the current topic, but that doesn't seem to add up either.

things do get recycled after all (without keep) have been used up?

**Comment by Lewwwk** [comment]
@dcsan I'd be happy to help more specifically, but respectfully, please read the docs first. They aren't perfect but reading will get you up to speed with a basic understanding so you can be productive with superscript.

**Comment by silentrob** [comment]
WRT un-scored topic weights. This is random non as there is no direction and I agree we could do a better job weighting them. Im looking at opening up the TF-IDF to the entire document.

**Comment by dcsan** [comment]
OK I figured out the issue - I was using `parse` each time, but that was just adding new topics; I'm now using `cleanup`. So probly having lots of dupes was causing the system weighting to freak out.

@Lewwwk sure, I'll go over the docs again. there are relevant points linked above tho

but the issue around {keep}  `> topic:system:keep ` is still confusing.

@silentrob 
> WRT un-scored topic weights

by this you mean that for `topics` (not triggers) there is no way to apply a weighting currently?

**Comment by silentrob** [comment]
Correct, right now topics are not weighted, they are scored by using tf-idf on the keywords.

**Comment by Lewwwk** [comment]
@dcsan from the docs: https://github.com/silentrob/superscript/wiki/Topics#topic-flags

> `keep` is designed to disable to default behavior of exhausting triggers, if you want the bot to say things over and over again, and apply keep just after the topic definition. Note that pre and post Topic Hooks automatically use this behaviour.

> `system` topics do not appear in the normal topic flow and you must provide your own way to access them, usually the `^respond(topic_name)` function works great for that. See Plugins and Functions
