### ISSUE TITLE
pre topic hook processes inputs in a loop

### ISSUE THREAD

**Issue by xumx** [silentrob/superscript#254]
```
> pre
  + *
  - ^pluginA()
< pre

+ hello
- world
```

```
exports.pluginA = function(text, cb) {
  cb(null, "{@hello}")
}
```

this code goes into a loop

**Comment by silentrob** [comment]
What happens when you do:
```
exports.pluginA = function(text, cb) {
  cb(null, "^topicRedirect(random, hello)")
}
```
I think that will go directly without re-processing

**Comment by xumx** [comment]
^topicRedirect seems to fail for a different reason

```
wvbot/node_modules/superscript/lib/reply/topicRedirect.js:86
                replyObj.reply.reply = reply;
                                     ^
TypeError: Cannot set property 'reply' of null
    at Promise.<anonymous> 
Desktop/wvbot/node_modules/superscript/lib/reply/topicRedirect.js:86:38)
```

**Comment by silentrob** [comment]
Okay, I will have a look at that as well. You mentioned you were using Wit.ai. Can you explain your use case so I can take that into account as well.

**Comment by zehfernandes** [comment]
My guess is when the Bot doesn't find anything to reply.
I fix with `{keep}` in the message at redirect topic.

**Comment by xumx** [comment]
Yes. ^topicRedirect( ) works without re-processing. In the above example it will work.

But in a real case it has to go directly to the correct topic. It is tricky to anticipate the topic while in the pre-step. Setting topic to random will trigger the above error. Because the Bot doesn't find anything to reply in random.
