### ISSUE TITLE
Last saved input stays in memory and crashes if variable is referenced before another save function is called

### ISSUE THREAD

**Issue by planetceres** [silentrob/superscript#259]
Gambits that use `^save` (i.e. `^save(firstName)`) seem to crash Superscript when you call a function to check for their presence (i.e. `^hasFirstName`) _unless_ another `save` function is called before the custom function. 

It looks like maybe Superscript is retaining the last called `^save` function and, as a result, passing the wrong variables to `lib/reply/customFunction.js` instead of the custom function.

During crash, logging from `lib/reply/customFunction.js` on line 6 shows:

    module.exports = function (reply, match, options, callback) {
      console.log(reply) // shows up as `save`
      console.log(match) // shows up as `firstName`
      console.log(options) // shows up as `[Function: customFunctionHandle]`
    });

**Example**

Conversation starts as expected but crashes when `^hasFirstName` function is called:

    You: Hello Bot
    Bot: Hello! I'm Bot. What's your name?
    You: Casey
    Bot: Nice to meet you, Casey!
    You: Hi Bot 
    [Crashes here]

Error logs
    
       /botproject /node_modules/superscript/plugins/user.js:11
              cb(null,"");
              ^

    TypeError: cb is not a function
        at /botproject/node_modules/superscript/plugins/user.js:11:11
        at /botproject/node_modules/superscript/node_modules/sfacts/node_modules/level-sublevel/shell.js:92:46
        at /botproject/node_modules/superscript/node_modules/sfacts/node_modules/level-sublevel/nut.js:108:13

_Unless_ the conversation goes like this:

    You: Hello Bot
    Bot: Hello! I'm Bot. What's your name?
    You: Casey
    Bot: Nice to meet you, Casey!
    You: Do you have my phone number?
    Bot: Would you like me to save your phone number?
    You: Yes
    Bot: What is your number?
    You: 9876543210
    Bot: Ok 9876543210. I'll save that.
    You: Hi Bot 
    Bot: Hello!
    [No crash!]

main.ss

    > topic:keep main
 
     + ~emohello [bot]
      - {^hasFirstName(true)} {keep} Hello!
      - {^hasFirstName(false)} {keep} Hello! ^topicRedirect(user_intro, intro)

      + * my phone number *
      - {^hasUserPhone(false)} Would you like me to save your phone number?
      - {^hasUserPhone(true)} I have your phone number as ^get(userPhone).

  	    + ~no
  	    % would you like me to save your phone number
  	    - ok.

  	    + ~yes
  	    % would you like me to save your phone number
  	    - ^topicRedirect(phone_capture, confirm_number)

    < topic

    > topic user_intro

  	  + intro
  	  - {keep} I'm Bot. What's your name?

	  + [my name is|i am] *1
	  % im bot whats your name
	  - {keep} Nice to meet you, <cap1>! ^save(firstName, <cap1>)

    < topic

    > topic phone_capture

	  + confirm_number
	  - {^hasUserPhone(false)} {keep} What is your number?
	  - {^hasUserPhone(true)} {keep} Your number is ^get(userPhone)

  	  + *~14
  	  % what is your number
  	  - Ok <cap1>. I'll save that. ^save(userPhone, <cap1>)
	
    < topic

custom function (`botproject/plugins/custom.js`):

    exports.hasFirstName = function(bool, cb) {
      this.user.getVar('firstName', function(e,name){
        if (name != null) {
          cb(null, (bool == "true") ? true : false)
        } else {
          cb(null, (bool == "false") ? true : false)
        }
      });
    }

    exports.hasUserPhone = function(bool, cb) {
      this.user.getVar('userPhone', function(e,name){
        if (name != null) {
          cb(null, (bool == "true") ? true : false)
        } else {
          cb(null, (bool == "false") ? true : false)
        }
      });
    }

**Comment by silentrob** [comment]
Thanks for the detailed issue. I will try to reproduce it and see if we can get to the bottom of it.

**Comment by planetceres** [comment]
It could well be I'm using functions incorrectly since the documentation isn't fully developed yet, but I'm running into a lot of problems using functions as described in the wiki, gists and testing framework. I also haven't been successful in pinpointing the problem more precisely in the Superscript module itself.

I don't know if this helps, but this issue looks like it could also be related to another I've been seeing while using functions in catch-alls. For instance, using the same gambits as above, Superscript crashes if the catch-all is a function:

    > topic:keep main

       + ~emohello [bot]
        - {^hasFirstName(true)} {keep} Hello!
        - {^hasFirstName(false)} {keep} Hello! ^topicRedirect(user_intro, intro)

        + *
        - {keep} ^getCatchAll

    < topic

Whereas, this seems to be okay:

    > topic:keep main

       + ~emohello [bot]
        - {^hasFirstName(true)} {keep} Hello!
        - {^hasFirstName(false)} {keep} Hello! ^topicRedirect(user_intro, intro)

        + *
        - {keep} I don't understand.

    < topic

The error I'm seeing in this instance looks something like this:

    /botproject/node_modules/superscript/lib/reply/topicRedirect.js:86
                replyObj.reply.reply = reply;
                                     ^

    TypeError: Cannot set property 'reply' of null
    at /botproject/node_modules/superscript/lib/reply/topicRedirect.js:86:38

**Comment by silentrob** [comment]
I'm working though this now, and it doesn't seem to be related to the filterFunction but I think a combination of the missing `catchaAll` function with the redirect. I also don't believe this is related to GH-262.
