### ISSUE TITLE
UTF8 support?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#26]
a little related to #16 - I tried typing in some double byte characters to the telnet client, and the data was mangled. Since my terminal is setup for unicode, some googling said this is a problem at socket setup, in that what I am seeing as i type input is being echoed back from the server?

I added this line line but no effect so wonder if its something deeper in the engine that is locked to ascii?

```js
  var newSocket = function (socket) {
    socket.setEncoding('utf8');   // no effect

```

eg typing in 日本語 shows like:

![image](https://cloud.githubusercontent.com/assets/514002/5441150/09dbe5c8-8443-11e4-863f-754792068fc9.png)

**Comment by silentrob** [comment]
This is now fixed. I removed double byte characters in at the normalizer layer.

**Comment by silentrob** [comment]
For reference - https://github.com/silentrob/normalizer/blob/master/test/basic.js#L63-L67
