### ISSUE TITLE
Capture processed as wordnet crashes bot.

### ISSUE THREAD

**Issue by Lewwwk** [silentrob/superscript#262]
In the case of an input capture like this:

```
+ *(1-6)
- ^save(name, <cap>)
```

When passing an input that gets processed by wordnet (e.g. `yes`), the bot will crash: 

```  
SS:ProcessHelpers Wordnet Replies +439ms []
  SS:ProcessHelpers Wordnet Replies +0ms []
  SS:ProcessHelpers Wordnet Replies +0ms []
  SS:ProcessHelpers Wordnet Replies +0ms []
  SS:Utils Trim +1ms name,  name,
  SS:Reply:customFunction Calling Plugin Function +0ms save
/.../node_modules/superscript/plugins/user.js:16
        cb(null, "");
        ^

TypeError: cb is not a function
    at /.../node_modules/superscript/plugins/user.js:16:9
    at /.../node_modules/level-sublevel/shell.js:92:46
    at /.../node_modules/level-sublevel/nut.js:108:13
```

If, however, there is a word in front of the capture, the reply process as expected with similar input (eg. `test yes`).
```
+ test *(1-6)
- ^save(name, <cap>)
```

**Comment by planetceres** [comment]
I'm pretty sure this is related to https://github.com/silentrob/superscript/issues/259.

I've noticed that if I log the capture, on occasion I get the function for `customFunctionHandler` instead of the expected text string. This usually happens when capturing data from within a topic or within a conversation. 

**Example:**

    > topic:nostay:system weather
	   + city
	   - {keep} What city were you looking for? 

		  + *~3
		  % what city were you looking for
		  - ^getWeather(<cap1>) {END} 

    < topic


plugins/custom.js

    exports.getWeather = function(query, cb) {
        console.log("Query: " + query)
        cb(null, "It's sunny in " + query + " right now.")
    }

**No Crash**

What I've noticed is that it depends on the input string as to whether or not `customFunctionHandler` gets caught as `<capN>`:

    You: Bot what's the weather?
    Bot: What city were you looking for? 
    You: San Francisco
    Bot: It's sunny in San Francisco right now.
    [No Crash]

The log shows:

    Query: San Francisco

**Crash**

But use a concept like `~emohello` to answer the question:

    You: Bot what's the weather?
    Bot: What city were you looking for? 
    You: Hello 
    [Crash]

The log shows:

    Query: function customFunctionHandle(err, subreply, matchBit) {

          var replyStr;

          if (_.isPlainObject(subreply)) {
            if (subreply.hasOwnProperty('text')) {
              replyStr = subreply.text;
              delete subreply.text;
            }

            if (subreply.hasOwnProperty('reply')) {
              replyStr = subreply.reply;
              delete subreply.reply;
            }
            scope.message.props = _.assign(scope.message.props, subreply);

          } else {
            replyStr = subreply;
          }

          match = false;
          reply = reply.replace(main, replyStr);
          match = reply.match(/\^(\w+)\(([~\w<>,\s]*)\)/);
          mbit = matchBit;
          if (err) {
            cb(err);
          } else {
            cb();
          }
        }

**Comment by Lewwwk** [comment]
@silentrob confirmed that bot does not crash any more.  Is it possible though to also have the capture be the original input rather than the word net equivalent?

Currently, entering

> hi

Results in a capture of 

> emohello

![screenshot 2016-04-16 12 28 59](https://cloud.githubusercontent.com/assets/42130/14582314/30b6d3ee-03cf-11e6-894a-94e26c080ff7.png)

(can create a separate issue if you prefer)

**Comment by silentrob** [comment]
This is a much bigger problem, is most cases that isn't a problem, but because of the way the system works normalizer replaces the original and we loose the semantic value of what was originally said.
