### ISSUE TITLE
persist users db and state

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#31]
We want to be able to save and reload user data when someone re-connects or has been gone for some period of time, or the bot engine restarts. 
Mongo or couch seems to make sense ill explore other options as well. JSON + lightweight.

**Comment by dcsan** [comment]
i'd prefer mongo. i intend to use this system with meteorJS which pretty much has mongo baked in...

**Comment by silentrob** [comment]
It would be nice to leverage one of the DB's already in place. LevelDB is pretty much a requirement right now, and we already offload the users saved data. 

I think the store really only needs to keep the user.name (which will be renamed to id in a upcoming release) and maybe a timestamp. The last 30 messages are very temporal and don't need to be saved.

**Comment by samuelazran** [comment]
Will it be possible to have some generic interface to the database that can be configurable or adapted for any DB?
For example for development environment simple json files will be enough, but on prduction environment one will be able to configure redis or mongoDB or whatever else.
I'm not yet familiar with the code of SuperScript. But if you expose simple read / write / update / delete API I will be able to hook the DB of my choice.

**Comment by dcsan** [comment]
until there are real scale requirements it would be nice to keep deployment simple, hence mongo.

**Comment by silentrob** [comment]
I opted for Mongo and published it to 0.4.0.
