### ISSUE TITLE
Update docs to for 0.3.x changes

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#33]

**Comment by silentrob** [comment]
Your welcome! Just a heads up the docs are a little out of date. 

## API changes

- Topic Includes and mixins are gone.
- Redirecting to a new topic is not required as it will be included automatically.

## New Features

- New Topic API
- Hidden topics
- Respond function

**Comment by dcsan** [comment]
> Redirecting to a new topic is not required as it will be included automatically.

I'm still using  it like:

    - You, wake up! {topic=inspector}

but not getting the topic change. is there some new way to use that?

**Comment by silentrob** [comment]
Docs have been updated
