### ISSUE TITLE
Redirecting reply gets "undefined"

### ISSUE THREAD

**Issue by samuelazran** [silentrob/superscript#35]
Base on this section in the docs:
http://superscriptjs.com/documentation/scripting#redirect
I've created this script:
main.ss:

    + ~emohello
    - Hi! {@ask}
    - Hello, {@ask}
    - Howdy, {@ask}
    - Ola, {@ask}
    
    + ask
    - How are you?
    - How you doing?
    - What's up?
    
But the result is:

>You> hi
>Bot> Howdy, undefined
>You> Hello
>Bot> Hello, undefined

And the debug log from the server:

    $ DEBUG=*,-Utils node server.js
    Script Loading Plugin +0ms ./plugins oppisite
    Script Loading Plugin +4ms ./plugins rhymes
    Script Loading Plugin +0ms ./plugins syllable
    Script Loading Plugin +0ms ./plugins letterLookup
    Script Loading Plugin +0ms ./plugins wordLength
    Script Loading Plugin +4ms ./plugins nextNumber
    Script Loading Plugin +0ms ./plugins createFact
    Script Loading Plugin +1ms ./plugins resolveAdjective
    Script Loading Plugin +0ms ./plugins evaluateExpression
    Script Loading Plugin +0ms ./plugins numToRoman
    Script Loading Plugin +0ms ./plugins numToHex
    Script Loading Plugin +0ms ./plugins numToBinary
    Script Loading Plugin +0ms ./plugins numMissing
    Script Loading Plugin +0ms ./plugins numSequence
    Script Loading Plugin +0ms ./plugins hasName
    Script Loading Plugin +0ms ./plugins has
    Script Loading Plugin +0ms ./plugins findLoc
    Script Loading Plugin +0ms ./plugins tooAdjective
    Script Loading Plugin +0ms ./plugins usedFor
    Script Loading Plugin +0ms ./plugins resolveFact
    Script Loading Plugin +0ms ./plugins putA
    Script Loading Plugin +0ms ./plugins isA
    Script Loading Plugin +0ms ./plugins colorLookup
    Script Loading Plugin +0ms ./plugins makeChoice
    Script Loading Plugin +0ms ./plugins findMoney
    Script Loading Plugin +0ms ./plugins findDate
    Script Loading Plugin +0ms ./plugins locatedAt
    Script Loading Plugin +0ms ./plugins aquireGoods
    Script Loading Plugin +0ms ./plugins bail
    Script Loading Plugin +1ms ./plugins one
    Script Loading Plugin +0ms ./plugins num
    Script Loading Plugin +0ms ./plugins changetopic
    Script Loading Plugin +0ms ./plugins changefunctionreply
    Script Loading Plugin +0ms ./plugins getDOW
    Script Loading Plugin +0ms ./plugins getDate
    Script Loading Plugin +0ms ./plugins getDateTomorrow
    Script Loading Plugin +0ms ./plugins getSeason
    Script Loading Plugin +0ms ./plugins getTime
    Script Loading Plugin +0ms ./plugins getTimeOfDay
    Script Loading Plugin +0ms ./plugins getDayOfWeek
    Script Loading Plugin +0ms ./plugins getMonth
    Script Loading Plugin +0ms ./plugins save
    Script Loading Plugin +0ms ./plugins get
    Script Loading Plugin +0ms ./plugins createUserFact
    Script Loading Plugin +0ms ./plugins wordnetDefine
    Script Loading Plugin +0ms ./plugins plural
    Script Loading Plugin +0ms ./plugins not
    Script Loading Plugin +1ms ./plugins lowercase
    Normalizer Loaded File +0ms { key: '_sys', file: 'systemessentials.txt' }
    Normalizer Loaded File +5ms { key: '_extra', file: 'substitutes.txt' }
    Normalizer Loaded File +333ms { key: '_contractions', file: 'contractions.txt' }
    Normalizer Loaded File +18ms { key: '_interjections', file: 'interjections.txt' }
    Normalizer Loaded File +76ms { key: '_britsh', file: 'british.txt' }
    Normalizer Loaded File +132ms { key: '_spellfix', file: 'spellfix.txt' }
    Normalizer Loaded File +776ms { key: '_texting', file: 'texting.txt' }
    Normalizer Done Reading Subs +18ms
    Normalizer Done Loading files +0ms
    Script Questions Loaded +1s
    Script System Loaded, waiting for replies +1ms
TCP server running on port 2000.

User '127.0.0.1:55582' has connected.

    Script Connecting User +7s 127.0.0.1:55582
    User user Connected +0ms { name: '127.0.0.1:55582',
    status: 1,
    currentTopic: 'random',
    memory: 
     { conceptToList: [Function],
         create: [Function],
         db: 
            { getStream: [Function],
                get: [Function],
                put: [Function],
                del: [Function],
                putStream: [Function],
                delStream: [Function],
                close: [Function],
                v: [Function: Variable],
                searchStream: [Function],
                search: [Function],
                isOpen: [Function],
                nav: [Function],
                generateBatch: [Function: generateBatch],
                joinStream: [Function],
                join: [Function],
                approximateSize: [Function] },
         createUserDB: [Function],
         createUserDBWithData: [Function] },
    conversationStartedAt: Fri Jan 16 2015 13:29:42 GMT+0000 (UTC),
    lastMessageSentAt: null,
    volley: 0,
    rally: 0,
    __history__: 
     { input: [ , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,    ],
         reply: [ , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,    ],
         topic: [ , , , , , , , , , , , , , , , , , , , , , , , , , , , , ,    ] } }
    Script Message Recieved from '127.0.0.1:55582' +5s hi
    Message Creating message from: +0ms ~emohello
    Message fullnames +975ms names []
    Message Fetch List +1ms
    Message Return with    +0ms []
    Message fullnames +1ms nouns []
    Message Things +0ms [ '~emohello' ]
    Message Things +0ms []
    Message Message +1ms { facts: 
     { conceptToList: [Function],
         create: [Function],
         db: 
            { breadthFirst: [Function: breadthFirst],
                deepFirst: [Function: deepFirst] },
         createUserDB: [Function],
         createUserDBWithData: [Function] },
    createdAt: Fri Jan 16 2015 13:29:49 GMT+0000 (UTC),
    raw: '~emohello',
    clean: '~emohello',
    crc: 'a5926307',
    dict: { words: [ [Object] ] },
    words: [ '~emohello' ],
    cwords: [ '~emohello' ],
    taggedWords: 
     [ [ '~emohello', 'NN' ],
         pushUnique: [ [Function], [Function] ],
         chunk: [ [Function], [Function] ] ],
    lemWords: [ '~emohello' ],
    lemString: '~emohello',
    posString: 'NN',
    qtype: '',
    qSubType: '',
    isQuestion: false,
    sentiment: 0,
    nouns: [ '~emohello' ],
    names: [],
    list: [],
    adjectives: [],
    adverbs: [],
    verbs: [],
    pnouns: [],
    pronouns: [],
    compareWords: [],
    numbers: [],
    compare: false,
    date: null,
    cNouns: [ '~emohello' ],
    numericExp: false,
    halfNumericExp: false,
    entities: [ '~emohello' ] }
    User getTopic +7s random
    Topics allTopics +0ms [ '__pre__', 'random', '__post__' ]
    GetReply Topics to check +0ms [ '__pre__', 'random', '__post__' ]
    Topic FindMatch +0ms random
    Topic Try to match (clean)'~emohello' against ~emohello (~emohello) topic: random +1ms
    Topic Try to match (lemma)'~emohello' against ~emohello (~emohello) topic: random +0ms
    Topic Found Match with topic random +0ms
    Topic Try to match (clean)'~emohello' against ask (ask) topic: random +1ms
    Topic Try to match (lemma)'~emohello' against ask (ask) topic: random +0ms
    GetReply match itor +2ms { stars: [],
    trigger: 
     { id: 'a5926307',
         trigger: '~emohello',
         replies: 
            { '20c01f40': 'Hi! {@ask}',
                '6f26a364': 'Hello, {@ask}',
                c4cb7385: 'Howdy, {@ask}',
                '8b163f90': 'Ola, {@ask}' },
         redirect: false,
         isQuestion: false,
         qType: false,
         qSubType: false,
         filter: false },
    topic: 'random' }
    GetReply filterRepliesByFunction +1ms [ { crc: '20c01f40',
        stars: [],
        topic: 'random',
        reply: 'Hi! {@ask}',
        trigger_id: 'a5926307' },
    { crc: '6f26a364',
        stars: [],
        topic: 'random',
        reply: 'Hello, {@ask}',
        trigger_id: 'a5926307' },
    { crc: 'c4cb7385',
        stars: [],
        topic: 'random',
        reply: 'Howdy, {@ask}',
        trigger_id: 'a5926307' },
    { crc: '8b163f90',
        stars: [],
        topic: 'random',
        reply: 'Ola, {@ask}',
        trigger_id: 'a5926307' } ]
    GetReply filterByFunction Results +2ms [ { crc: '20c01f40',
        stars: [],
        topic: 'random',
        reply: 'Hi! {@ask}',
        trigger_id: 'a5926307' },
    { crc: '6f26a364',
        stars: [],
        topic: 'random',
        reply: 'Hello, {@ask}',
        trigger_id: 'a5926307' },
    { crc: 'c4cb7385',
        stars: [],
        topic: 'random',
        reply: 'Howdy, {@ask}',
        trigger_id: 'a5926307' },
    { crc: '8b163f90',
        stars: [],
        topic: 'random',
        reply: 'Ola, {@ask}',
        trigger_id: 'a5926307' } ]
    GetReply filterRepliesBySeen +1ms [ { crc: '20c01f40',
        stars: [],
        topic: 'random',
        reply: 'Hi! {@ask}',
        trigger_id: 'a5926307' },
    { crc: '6f26a364',
        stars: [],
        topic: 'random',
        reply: 'Hello, {@ask}',
        trigger_id: 'a5926307' },
    { crc: 'c4cb7385',
        stars: [],
        topic: 'random',
        reply: 'Howdy, {@ask}',
        trigger_id: 'a5926307' },
    { crc: '8b163f90',
        stars: [],
        topic: 'random',
        reply: 'Ola, {@ask}',
        trigger_id: 'a5926307' } ]
    GetReply Bucket +0ms [ { crc: '20c01f40',
        stars: [],
        topic: 'random',
        reply: 'Hi! {@ask}',
        trigger_id: 'a5926307' },
    { crc: '6f26a364',
        stars: [],
        topic: 'random',
        reply: 'Hello, {@ask}',
        trigger_id: 'a5926307' },
    { crc: 'c4cb7385',
        stars: [],
        topic: 'random',
        reply: 'Howdy, {@ask}',
        trigger_id: 'a5926307' },
    { crc: '8b163f90',
        stars: [],
        topic: 'random',
        reply: 'Ola, {@ask}',
        trigger_id: 'a5926307' } ]
    ProcessTags Inline redirection to: ask +0ms
    GetReply Called Recursively +4ms 1
    User getTopic +11ms random
    Topics allTopics +11ms [ '__pre__', 'random', '__post__' ]
    GetReply Topics to check +0ms random
    ProcessTags CallBack from inline redirect +2ms undefined
    ProcessTags CallBack from inline redirect +1ms Howdy, undefined
    GetReply err, reply +2ms null Howdy, undefined
    Message Creating message from: +16ms Howdy, undefined
    Message fullnames +311ms names []
    Message Fetch List +0ms
    Message Return with    +0ms []
    Message fullnames +7ms nouns []
    Message Things +0ms [ '~emohello' ]
    Message Things +0ms []
    Message Message +1ms { facts: 
     { conceptToList: [Function],
         create: [Function],
         db: 
            { breadthFirst: [Function: breadthFirst],
                deepFirst: [Function: deepFirst] },
         createUserDB: [Function],
         createUserDBWithData: [Function] },
    createdAt: Fri Jan 16 2015 13:29:50 GMT+0000 (UTC),
    raw: 'Howdy, undefined',
    clean: '~emohello, undefined',
    crc: '84658c97',
    dict: { words: [ [Object], [Object], [Object] ] },
    words: [ '~emohello', ',', 'undefined' ],
    cwords: [ '~emohello', ',', 'undefined' ],
    taggedWords: 
     [ [ '~emohello', 'NN' ],
         [ ',', ',' ],
         [ 'undefined', 'JJ' ],
         pushUnique: [ [Function], [Function] ],
         chunk: [ [Function], [Function] ] ],
    lemWords: [ '~emohello', ',', 'undefined' ],
    lemString: '~emohello , undefined',
    posString: 'NN , JJ',
    qtype: '',
    qSubType: '',
    isQuestion: false,
    sentiment: 0,
    nouns: [ '~emohello' ],
    names: [],
    list: [],
    adjectives: [ 'undefined' ],
    adverbs: [],
    verbs: [],
    pnouns: [],
    pronouns: [],
    compareWords: [],
    numbers: [],
    compare: false,
    date: null,
    cNouns: [ '~emohello' ],
    numericExp: false,
    halfNumericExp: false,
    entities: [ '~emohello' ] }
    User Updating History +324ms
    User getTopic +0ms random
    Script Update and Reply to user '127.0.0.1:55582' +2s Howdy, undefined
    Script Message Recieved from '127.0.0.1:55582' +5.4m Hello
    Message Creating message from: +5.4m ~emohello
    Message fullnames +115ms names []
    Message Fetch List +0ms
    Message Return with    +1ms []
    Message fullnames +0ms nouns []
    Message Things +0ms [ '~emohello' ]
    Message Things +0ms []
    Message Message +0ms { facts: 
     { conceptToList: [Function],
         create: [Function],
         db: 
            { breadthFirst: [Function: breadthFirst],
                deepFirst: [Function: deepFirst] },
         createUserDB: [Function],
         createUserDBWithData: [Function] },
    createdAt: Fri Jan 16 2015 13:35:15 GMT+0000 (UTC),
    raw: '~emohello',
    clean: '~emohello',
    crc: 'a5926307',
    dict: { words: [ [Object] ] },
    words: [ '~emohello' ],
    cwords: [ '~emohello' ],
    taggedWords: 
     [ [ '~emohello', 'NN' ],
         pushUnique: [ [Function], [Function] ],
         chunk: [ [Function], [Function] ] ],
    lemWords: [ '~emohello' ],
    lemString: '~emohello',
    posString: 'NN',
    qtype: '',
    qSubType: '',
    isQuestion: false,
    sentiment: 0,
    nouns: [ '~emohello' ],
    names: [],
    list: [],
    adjectives: [],
    adverbs: [],
    verbs: [],
    pnouns: [],
    pronouns: [],
    compareWords: [],
    numbers: [],
    compare: false,
    date: null,
    cNouns: [ '~emohello' ],
    numericExp: false,
    halfNumericExp: false,
    entities: [ '~emohello' ] }
    User getTopic +5.4m random
    Topics allTopics +5.4m [ '__pre__', 'random', '__post__' ]
    GetReply Topics to check +5.4m [ '__pre__', 'random', '__post__' ]
    Topic FindMatch +5.4m random
    Topic Try to match (clean)'~emohello' against ~emohello (~emohello) topic: random +0ms
    Topic Try to match (lemma)'~emohello' against ~emohello (~emohello) topic: random +0ms
    Topic Found Match with topic random +0ms
    Topic Try to match (clean)'~emohello' against ask (ask) topic: random +1ms
    Topic Try to match (lemma)'~emohello' against ask (ask) topic: random +0ms
    GetReply match itor +2ms { stars: [],
    trigger: 
     { id: 'a5926307',
         trigger: '~emohello',
         replies: 
            { '20c01f40': 'Hi! {@ask}',
                '6f26a364': 'Hello, {@ask}',
                c4cb7385: 'Howdy, {@ask}',
                '8b163f90': 'Ola, {@ask}' },
         redirect: false,
         isQuestion: false,
         qType: false,
         qSubType: false,
         filter: false },
    topic: 'random' }
    GetReply filterRepliesByFunction +0ms [ { crc: '20c01f40',
        stars: [],
        topic: 'random',
        reply: 'Hi! {@ask}',
        trigger_id: 'a5926307' },
    { crc: '6f26a364',
        stars: [],
        topic: 'random',
        reply: 'Hello, {@ask}',
        trigger_id: 'a5926307' },
    { crc: 'c4cb7385',
        stars: [],
        topic: 'random',
        reply: 'Howdy, {@ask}',
        trigger_id: 'a5926307' },
    { crc: '8b163f90',
        stars: [],
        topic: 'random',
        reply: 'Ola, {@ask}',
        trigger_id: 'a5926307' } ]
    GetReply filterByFunction Results +2ms [ { crc: '20c01f40',
        stars: [],
        topic: 'random',
        reply: 'Hi! {@ask}',
        trigger_id: 'a5926307' },
    { crc: '6f26a364',
        stars: [],
        topic: 'random',
        reply: 'Hello, {@ask}',
        trigger_id: 'a5926307' },
    { crc: 'c4cb7385',
        stars: [],
        topic: 'random',
        reply: 'Howdy, {@ask}',
        trigger_id: 'a5926307' },
    { crc: '8b163f90',
        stars: [],
        topic: 'random',
        reply: 'Ola, {@ask}',
        trigger_id: 'a5926307' } ]
    GetReply filterRepliesBySeen +0ms [ { crc: '20c01f40',
        stars: [],
        topic: 'random',
        reply: 'Hi! {@ask}',
        trigger_id: 'a5926307' },
    { crc: '6f26a364',
        stars: [],
        topic: 'random',
        reply: 'Hello, {@ask}',
        trigger_id: 'a5926307' },
    { crc: 'c4cb7385',
        stars: [],
        topic: 'random',
        reply: 'Howdy, {@ask}',
        trigger_id: 'a5926307' },
    { crc: '8b163f90',
        stars: [],
        topic: 'random',
        reply: 'Ola, {@ask}',
        trigger_id: 'a5926307' } ]
    GetReply Bucket +3ms [ { crc: '20c01f40',
        stars: [],
        topic: 'random',
        reply: 'Hi! {@ask}',
        trigger_id: 'a5926307' },
    { crc: '6f26a364',
        stars: [],
        topic: 'random',
        reply: 'Hello, {@ask}',
        trigger_id: 'a5926307' },
    { crc: 'c4cb7385',
        stars: [],
        topic: 'random',
        reply: 'Howdy, {@ask}',
        trigger_id: 'a5926307' },
    { crc: '8b163f90',
        stars: [],
        topic: 'random',
        reply: 'Ola, {@ask}',
        trigger_id: 'a5926307' } ]
    ProcessTags Inline redirection to: ask +5.4m
    GetReply Called Recursively +1ms 1
    User getTopic +9ms random
    Topics allTopics +9ms [ '__pre__', 'random', '__post__' ]
    GetReply Topics to check +2ms random
    ProcessTags CallBack from inline redirect +2ms undefined
    ProcessTags CallBack from inline redirect +0ms Hello, undefined
    GetReply err, reply +1ms null Hello, undefined
    Message Creating message from: +13ms Hello, undefined
    Message fullnames +120ms names []
    Message Fetch List +0ms
    Message Return with    +1ms []
    Message fullnames +1ms nouns []
    Message Things +0ms [ '~emohello' ]
    Message Things +1ms []
    Message Message +0ms { facts: 
     { conceptToList: [Function],
         create: [Function],
         db: 
            { breadthFirst: [Function: breadthFirst],
                deepFirst: [Function: deepFirst] },
         createUserDB: [Function],
         createUserDBWithData: [Function] },
    createdAt: Fri Jan 16 2015 13:35:15 GMT+0000 (UTC),
    raw: 'Hello, undefined',
    clean: '~emohello, undefined',
    crc: '73c66d71',
    dict: { words: [ [Object], [Object], [Object] ] },
    words: [ '~emohello', ',', 'undefined' ],
    cwords: [ '~emohello', ',', 'undefined' ],
    taggedWords: 
     [ [ '~emohello', 'NN' ],
         [ ',', ',' ],
         [ 'undefined', 'JJ' ],
         pushUnique: [ [Function], [Function] ],
         chunk: [ [Function], [Function] ] ],
    lemWords: [ '~emohello', ',', 'undefined' ],
    lemString: '~emohello , undefined',
    posString: 'NN , JJ',
    qtype: '',
    qSubType: '',
    isQuestion: false,
    sentiment: 0,
    nouns: [ '~emohello' ],
    names: [],
    list: [],
    adjectives: [ 'undefined' ],
    adverbs: [],
    verbs: [],
    pnouns: [],
    pronouns: [],
    compareWords: [],
    numbers: [],
    compare: false,
    date: null,
    cNouns: [ '~emohello' ],
    numericExp: false,
    halfNumericExp: false,
    entities: [ '~emohello' ] }
    User Updating History +129ms
    User getTopic +0ms random
    Script Update and Reply to user '127.0.0.1:55582' +372ms Hello, undefined

**Comment by silentrob** [comment]
Sorry this regressed yesterday. Ill have it working shortly.

**Comment by silentrob** [comment]
It is fixed in 0.3.13

Let me know if you bump into any other issues.

**Comment by samuelazran** [comment]
it works! thanks. and thanks for this awesome project!

**Comment by silentrob** [comment]
Your welcome! Just a heads up the docs are a little out of date. 
The TLDR is: 
API changes
- Topic Includes and mixins are gone.
- Redirecting to a new topic is not required as it will be included automatically.
New Features
- New Topic API
- Hidden topics
- Respond function

Ill try to update the docs this weekend.

**Comment by samuelazran** [comment]
So, how to navigate between topics? and more specifically: I'd like to redirect the reply to a specific reply in specific topic. something like:

    + ~emohello
    - {topic=weather}{@ask about the weather}

Looking forward for the updated docs,
Thanks

**Comment by silentrob** [comment]
This is a great question. And is technically not possible yet, but I would like to make it work.

So in your expression {topic=weather} will set the next expression to start looking for matches in the topic weather and does not aid the current request cycle.

And redirects only redirect within the current topic.

The other tool that gets us close to what you want is the respond function. 

    + * rain *
    - ^respond(weather)

Respond will jump into the weather topic and continue looking for matches based on the current input and return back to the topic it was last in if no input was found.

So in this case we don't change what we are searching for. 

Ideally we need to redirect to look across all topics for a match or have the ability to choose a topic.

It would be interesting to have something like this

    + ~emohello
    @say_something

    +say_something
    - ^topicRedirect(weather, __say_something__)
    - ^topicRedirect(work, __say_something__)

    > topic weather
      + __say_somthing__
      - I hate the rain, do you?
      - Have you ever tied to make shapes from the clouds
    < topic

In all cases _say_something_ is just a normal trigger.  

The other approach is to bring back the '*' command which is a say statement. Or like a unhinged reply.
But that gives a little less control over what would be said and would still require a function like `^redirectToTopicAndSay(weather)`

**Comment by samuelazran** [comment]
Wow. this is really cool that you can push upgrades so fast. I guess it's due to the flexibility of javascript :)

The function ^respond is ok for me, but ^topicRedirect is more precise and I've tested it this morning and it does the job for me. I'm translating a virtual agent I've wrote with ChatScript to SuperScript to see the differences.  

I don't seems to understand the meaning of "current topic" in SuperScript. seems to me (and correct me if I'm wrong) like the system will try to match every possible trigger to the input from every topic. so there is not much of a limited scope in here. in ChatScript the system will first check for responders / rejoinders in the "current topic" and if no match then it will look for a gambit in the current topic and only if none available then the system will try other topics (only if some words in the input match the topic keywords).

Thanks

**Comment by silentrob** [comment]
Oh you are familiar with ChatScript - cool.

So Im hoping to achieve the same style of system for how topics are found. 
Here is the actual code. 
https://github.com/silentrob/superscript/blob/master/lib/topics.js#L44-L92
We start with a pre topic, than the current topic, or topic they just matched in. Than we do a keyword search.

Here is an example of topics with keywords.
https://github.com/silentrob/superscript/blob/master/test/fixtures/topicsystem/main.ss#L18-L31

We don't really have a rejoin system but have a previous gambit (conversation) system, and we always search that topic before looking more broadly 

We sort those topics by relevance and included anything else non relevant after that. 
Finally we have a post topic hook at the end.

Superscript does not have a control script, but you can achieve something similar with the pre/post topics. 
We use a TF-IDF search of the keywords provided in the topic against the input to sort the relevant topics order.

I could see the need to not include all topics if the relevance score is low as it might take to long to process, and Im very open to suggestions on how to improve this.
