### ISSUE TITLE
web adapter (http / websockets)

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#39]
so i see you have slack & telnet by default, i was wondering if there:s a web driver?
i thought you had one in the previous release...

**Comment by silentrob** [comment]
https://github.com/silentrob/superscript-websocket-demo

**Comment by dcsan** [comment]
woah this is cool, a whole simple web front-end! i thought you just meant you added a websocket protocol driver.

![image](https://cloud.githubusercontent.com/assets/514002/5921618/12271788-a5fa-11e4-9837-24be53f2f867.png)

**Comment by silentrob** [comment]
I should have said somewhere it is a color demo. Type "what color is the sky"

**Comment by dcsan** [comment]
ok, now i'm starting to see some of the power of the MBs of conceptnet and other stuff you have.

FYI it will crash on unknown things, or maybe it's when an array of possible responses come back?


/Users/dc/dev/shumi/superscript-websocket-demo/node_modules/conceptnet/node_modules/knex/node_modules/bluebird/js/main/async.js:93
                throw res.e;
                         ^
TypeError: Cannot call method 'map' of undefined


![image](https://cloud.githubusercontent.com/assets/514002/5931208/0d4b7894-a64f-11e4-973d-70faaa396690.png)

![image](https://cloud.githubusercontent.com/assets/514002/5931211/3ee79cb6-a64f-11e4-90aa-66625b61db8d.png)
![image](https://cloud.githubusercontent.com/assets/514002/5931215/701369c8-a64f-11e4-871e-0301a4b91176.png)
