### ISSUE TITLE
replies get used up?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#41]
I noticed that sometimes the replies were blank, and I guess this is why:

> Replies can be stacked up and will be chosen at RANDOM. Once a reply has been used, we discard it and won't use it again. 

you mean permanently discarded? is there a way to stop this behavior, or to cycle through the replies in order? eg if I have an NPC in a shop, I want him to just keep repeating a set phrase like
 "Come back later I told ya"

**Comment by dcsan** [comment]
found the answer 

> Keep Flag
If you have a reply that needs to stick around after it has been said you need to mark it with the {keep} flag.

+ i say this
- {keep} this is a reply

**Comment by dcsan** [comment]
just to confirm if the empty situatino happens if there is only one reply?
if you have two or more will it bounce back and repeat even without :keep?


```

/*
	Keep Flag Test
	We use the keep flag to allow us to reuse the gambit over and over

*/
> topic:keep keeptopic
	+ i have one thing to say
	- topic test pass
< topic

```

**Comment by silentrob** [comment]
You are on track.

If you want to keep a reply use the {keep} flag on the reply, or you can apply it globally to the whole topic as you shown above.

The will come back into play after 10 messages. And they are not erased globally (for all users) just the current user.
