### ISSUE TITLE
how to send back the topic and other important info

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#42]
I'm trying to send JSON back with a bit more metadata about bot state.

is `bot.scope.user.pendingTopic,` the right field to send for currentTopic?
it doesn't seem to change as I would have thought (but that maybe a differnt issue)

```
    bot.reply(socket.name, message.trim(), function(err, reply){

      msg = {
        reply: reply,
        topic: bot.scope.user.pendingTopic,
        // bot: bot
      }
```

**Comment by silentrob** [comment]
This is now possible in 0.5.0 From the scripting interface use the function ^addMessageProp(key,value) 

Which is a shortcut for 

    this.message.props[key] = value; // from inside functions

That data will be passed back in the replyObject.
