### ISSUE TITLE
random topic is required?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#43]
http://superscriptjs.com/documentation/scripting#random

> All dialogue belongs to a topic and even if you do not use any topics, those triggers and replies will be stored in the random topic.

do i need a random topic? or just anything outside a topci will become random?

```
> topic random

  + *
  - You, wake up! {topic=inspector}

  ? *
  - why are you asking me?

< topic
```

**Comment by dcsan** [comment]
also is random (top level) content always included, no matter if there is another topic set?

I have a topic set according to debug output but still see entries from random too.

**Comment by silentrob** [comment]
Both ways work.

The only time you might want to create a random topic is if you want to override the topic flags.
