### ISSUE TITLE
capturing zero chars / generic wildcard?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#44]
I see in your tests:

    + [*]

> A generic wildcard character will match Zero to Unlimited characters, words or tokens, and the input is NOT captured or saved by the system.

so is

    + *

the right way to have a general starting off gambit?

also I'm assuming `(*)` means capture?

**Comment by dcsan** [comment]
not sure whats going on as i have a wildcard **inside** another topic, but that is getting picked up even when im in topic=undefined. 

also changing the topic has no effect.

```

> topic biker

  + [go] street
  - you go back into the street. {topic=street}

  + [*]
  - Yeah? Whaddaya want? says the biker.

< topic


You> ho
{"reply":"Yeah? Whaddaya want? says the biker."}
what
{"reply":"Yeah? Whaddaya want? says the biker."}
street
{"reply":"Yeah? Whaddaya want? says the biker."}

```

**Comment by dcsan** [comment]
FYI the test scripts are here.

https://github.com/dcsan/superbotz/blob/master/bot2/topics/biker.ss

OK  i think this is because the keys are sorted alphabetically?
so anything under "biker" is matching first?

**Comment by silentrob** [comment]
So a wildcard even inside another topic will still be found and fire if nothing matches before it.

Just a quick note about your first point 

    [*] vs *

[*] will capture the contents and make it available to <cap1>
Just a * will not be captured and returned as data.  The TLDR, if you don't want to save the output just use `*`

**Comment by silentrob** [comment]
capture and match are two different things as well.. the system will match because it is a greedy wildcard.. capture means the output is saved and available in <cap1> to be used in the reply.
