### ISSUE TITLE
sending back metadata / variables

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#45]
I recall you had some code for saving variables before (facts?) but cant see this in the tests dir.

is all content in { } suppressed? If i wanted to use the engine to return structured data, what would you think is the best way? eg:

    + hit biker
    - the biker hits you back { health: -2 }

    + scream
    - The biker shouts back { who: biker }

etc.

**Comment by silentrob** [comment]
I don't know what your building, but this looks awesome.
No not all `{ }` is stripped off.

If you want to save data you will want to use the triple store. and that requires a plugin or helper function.
There is two ways you can do it. Either key/value pairs or full triple facts - subject/ver/object.

There is a helper function ^save() and ^get() which will take you pretty far.

 
    + hit biker
    - the biker hits you back ^save(health,-2)

    + scream
    - The biker shouts back ^save(who,biker)

**Comment by silentrob** [comment]
This file is full of plugins and function and creating facts

https://github.com/silentrob/superscript/blob/master/test/fixtures/reason/main.ss#L106
