### ISSUE TITLE
changing topics

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#46]
not sure if the syntax has changed/parser broke/I'm doing something wrong, but i can't seem to get much joy out of the system.

```json

// ---------   inspector   --------------

> topic inspector

  + askticket
  - wheres your ticket? {topic=ticket}

  + hello
  - dont hello me.

  + * lost
  - "you're lost??! well, that's not my problem."

  ? * ticket
  - "Don't pretend. You know what I'm talking about!"

  // is there an order eg fallthru to last option?
  + [*]
  - pay attention! {@askticket}
  - "hey! I'm talking to you!" {@askticket}

< topic

// ------ ticket -----------

> topic ticket includes inspector

  + I lost [*]
  - you lost your ticket? {@getoff}

  + *
  - So? {@getoff}

  + getoff
  - You have to get off the train then {topic=street}

< topic

=========== gives:

You> hi
{"reply":"dont hello me.","currentTopic":"random"}
ok
{"reply":"pay attention! wheres your ticket?","currentTopic":"ticket","pendingTopic":"ticket"}
i lost it
{"reply":"pay attention! wheres your ticket?","currentTopic":"ticket","pendingTopic":"ticket"}
I lost it
{"reply":"pay attention! wheres your ticket?","currentTopic":"ticket","pendingTopic":"ticket"}
whatever
{"reply":"pay attention! wheres your ticket?","currentTopic":"ticket","pendingTopic":"ticket"}

```

**Comment by dcsan** [comment]
maybe the includes keywords are messing up the parser?
or the wildcards have to be in brackets?
not sure.

blob is here in case it helps to have a repro
https://github.com/dcsan/superbotz/blob/8498eedf03b1d0a2bad137ba6b87eaf6f08eab93/bot2/topics/inspector.ss

**Comment by silentrob** [comment]
I found the problem. We were not return the current topic to the topic System.
Fixed in 0.4.5

**Comment by silentrob** [comment]
I also added a IF example that demonstrates some basic navigation

https://github.com/silentrob/superscript/blob/master/example/if.ss

**Comment by dcsan** [comment]
this looks awesome!

**Comment by dcsan** [comment]
https://github.com/silentrob/superscript/blob/master/example/if.ss#L21
> 	// from any topic, we can fix that by adding a trigger filter function., now this trigger will only match 
>	// if you are in the room.

I think this might be confusing that you can be on another topic but still match.
so youre in topic=frontroom but somehow get a match on something fenced out as > topic backroom

i guess i need to understand a bit more how that priority match works. i think you were saying that the fact it was a recent topic (ie maybe you had been talking about that) also plays into the algo/priority?
perhaps i need to look at it with debug mode some more to see priorties of the candidates in each case.
