### ISSUE TITLE
[TODOC] commands at start of line only.

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#47]
if i use 

    + punch
    - he punches you back ^save(bikerAngry, true) {@look}

I see:

    You> punch
    Bot> he punches you back ^save(bikerAngry, true) he seems pretty chill.

so the command ^save is just coming out in the string?
but the `{@look}` redirect **after** that is working fine.

but if i put on runon using caret, eg two lines, the second line doesn't fire

    + punch
    - he punches you back ^save(bikerAngry, true) {@look}
    ^ {@look}

(look will never fire)

**Comment by dcsan** [comment]
ok got it commands have to be at the start of the line.

#documentMe

**Comment by dcsan** [comment]
meh, start of line doesn:t work either somehow

```
  + punch
  - ^save(bikerAngry, true) he punches you back
  ^ {@look}

  + (punch|hit|kick|bite) biker
  - {@punch}

dc [2:27 PM] 
punch

drifter [2:27 PM] 
^save(bikerAngry, true) he punches you backhe seems pretty chill.

```

**Comment by dcsan** [comment]
its the redirect that breaks this. single command works fine.

**Comment by silentrob** [comment]
Lets create a test for this and see if we can repo it.
So it should be custom functions and redirects playing together on one or spanning lines with carrot. 
Am I missing anything?

**Comment by dcsan** [comment]
yep, that seems to be the cause.

**Comment by dcsan** [comment]
i could take a crack at a test in a fork maybe. do you have a testrunner script, or how do i fire up your test suite? or ideally just a single test file/set ?

**Comment by silentrob** [comment]
Yes, Mocha
    npm test

Add it to either test/scripts.js (core functionality) or test/style.js (scripting style)

**Comment by silentrob** [comment]
Im going to close this. Editing files is going to be a thing of the past after 0.6.0
