### ISSUE TITLE
keep spaces at the end of entries

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#48]
detailed typography point!
how best to keep spaces in a line? eg after the ? mark here:

    Bot> biker: what do ya want?he seems pretty chill.

```
  + look
  - {^hasItem(bikerAngry, true)} he seems angry.
  - {^hasItem(bikerAngry, false)} he seems pretty chill.

  + talk *
  - biker: what do ya want? 
  ^ {@look}
```

note `want? ` does have a space but i guess it gets trimmed off.

**Comment by silentrob** [comment]
I feel like this was working at one time with \s. I will add a test for it.

**Comment by silentrob** [comment]
This should be good now. Add a \s and it will convert it to space.
