### ISSUE TITLE
Slack @Replies need to parse out the user name

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#50]
I added a slack client, but it seems to ignore most of the logic?

mostly just finds the wildcards.

![image](https://cloud.githubusercontent.com/assets/514002/5893524/9e037058-a49c-11e4-868f-de12e5f86cf5.png)

**Comment by dcsan** [comment]
hmm, its working now. i changed a bit of code in slack-server but nothing that *should* be relevant.

**Comment by silentrob** [comment]
I believe there is a bug with at replies.

**Comment by dcsan** [comment]
right, i removed the @reply stuff.

**Comment by jeffmarder** [comment]
Looks like it is on line 72 of clients/slack.js and was introduced in commit 6a256d7. The assignment is replacing an object with a string. Should be reply.string on left side. On mobile. Will check it out when I can.

**Comment by silentrob** [comment]
That commit is not related to the issue identified. While using the slack client you @bot from a general room, the message sends <@slackuserID> into bot and it should  probably be replaced with a string.

**Comment by jeffmarder** [comment]
Yeah, I was totally wrong about that one. There are a couple things going on in that file though. I have been experiencing another issue. The bot replies to direct messages, but it has trouble with stuff like "@bot hello". Off topic for this issue. Will send a patch soon.

**Comment by silentrob** [comment]
I did notice another little issue dealing with empty replies. I will push a patch for that.

**Comment by jeffmarder** [comment]
Yeah that's the one. If you already have it under control I won't bug you with the pull request. Thanks.

**Comment by silentrob** [comment]
No worries. that is pushed at tagged 0.5.2. I hope you didn't get burned and Ill be happy to take a pull request anytime!

**Comment by mariusursache** [comment]
Is this solved? Can it be closed?

**Comment by silentrob** [comment]
Ya I will close it. This is really outside the core of ss anyway.
