### ISSUE TITLE
trigger matching problems

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#53]
if post runs last im not sure why its catching everything here:

```

> post 

  + *
  - wildcard here. wassup

< post

// random

+ topic
- we were talking about {^getTopic()}

```

![image](https://cloud.githubusercontent.com/assets/514002/5893979/b8165072-a4ac-11e4-839a-780c0a85ac7c.png)

**Comment by dcsan** [comment]
ok i think this is cos {^getTopic()} was being a filter?

```

+ topic
- we were talking about: 
^ ^getTopic()

```

works

**Comment by silentrob** [comment]
That is correct
