### ISSUE TITLE
multiple true items?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#54]
I htink your filters will only pick one item after all the trues are parsed. how would i show a list of items?

```
> topic backpack

  + look
  - {^hasItem(wrench, true)} you have a wrench
  - {^hasItem(sandwich, true)} a moldy old sandwich
  ^ thats your stuff.

```

**Comment by silentrob** [comment]
The system sees..

    + look
    - {^hasItem(wrench, true)} you have a wrench
    - {^hasItem(sandwich, true)} a moldy old sandwich thats your stuff.

And picks ONE of the replies at random providing it passes the filter test.

What I think you are wanting to do is 

    + look
    - Your bag contains
    ^ {^hasItem(wrench, true)} you have a wrench
    ^ {^hasItem(sandwich, true)} a moldy old sandwich
    ^ thats your stuff.

This functionality does not exist today as we are not filtering out replies but parts of a already selected reply. I think this feature makes sense to add.

**Comment by silentrob** [comment]
This issue should be moved to the new editor and tracked there. If we get any more requests for it, we can look at implementing it in the web editor.
