### ISSUE TITLE
replace conversation system with something more robust

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#58]
Right now conversations work with the `%` command as in

    + say this
    - some reply

    + second match
    % some reply
    - follow up

The challenge with this is you need to repeat the reply, however the reply could be more complicated.
because it contains a filter function, or has been redirected to from another gambit.

My initial proposal is to include a reply label that can be used rather than the reply itself

    + say this
    - A: do you agree?

    + yes
    % A
    - C: good

    + no
    % A
    - D: too bad
   
    + third match
    % C
    - This is the end

Perhaps even supplying a short hand notation to collapse the reply label and new match onto the same line 

    + say this
    - A: do you agree?

    % A: yes
    - C: good

    % A: no
    - D: too bad

    % C: what about my follow up
    - there is no follow up

You could even combined the labels for reuse like this

    + say this
    - A: do you agree?

    + Im hungry
    - X: Did you pick up dinner?

    % A:X: yes
    - C: good

    % A:X: no
    - D: too bad

**Comment by samuelazran** [comment]
Good idea!
Just like ChatScript's rejoinder. you don't want to repeat the last output completely when you want to force the system to prefer a specific response, could be useful also for in topic redirect.

It will be more flexible than ChatScript because you don't have to nest the rejoinder under the main trigger/reply.

**Comment by silentrob** [comment]
This has now been replaced by the new topic system and enhanced with the editor.
