### ISSUE TITLE
docs or suggestion where to look on more advanced features?

### ISSUE THREAD

**Issue by dcsan** [silentrob/superscript#59]
the websocket demo you did recently blew me away with the functionality in one line of code:

```
?:ENTY:color *
- ^colorLookup()
```

but there isn't much docs to this on the main site? Are there any other examples to look for this? I guess maybe your tests is the best place to start?

**Comment by silentrob** [comment]
It is documented here
http://superscriptjs.com/documentation/scripting.html#answer

And in the tests here 
https://github.com/silentrob/superscript/blob/master/test/qtype.js
https://github.com/silentrob/superscript/blob/master/test/fixtures/qtype/main.ss
