### ISSUE TITLE
Data Importer

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#63]
We need a way to import data into the new mongo schema.

**Comment by dcsan** [comment]
what is actually kept in mongo? is it the bot script itself, the post process JSON, or the other facts etc database?

if the JSON is in mongo, that would mean it would be possible to make a way to reload data on the fly, which would be huge for rapid development. and also being able to put a "try superscript in your browser!"  demo app together like:
http://www.rivescript.com/try

**Comment by silentrob** [comment]
RiveScript Try works because RiveScript runs in the client (as well as the server)

I will be storing the actual topics, gambits and replies as documents. Something that is like the JSON that the parser generates but further processed.

As it is now, that data is generated into models on the fly already and stored in memory, and you can dynamically create new topics, and gambits and add to the system. However because it is in memory, we can't export it back out to the chat script format to continue to edit. This is really the goal of the milestone to tighten the loop all the way down to real-time.
