### ISSUE TITLE
Installation dependency issue with conceptnet

### ISSUE THREAD

**Issue by arunbahl** [silentrob/superscript#65]
I've been unable to install the conceptnet dependency, and a search on npmjs.com shows it as not found.
https://www.npmjs.com/search?q=conceptnet
Was this supposed to be "concept-net" or am I doing something wrong?

**Comment by silentrob** [comment]
It is a local (github) dependancy conceptnet": "silentrob/conceptnet" and is actually not even needed in core. I use it for some tests and more advanced reasoning stuff but that is about it.

You can remove it or it should come in from github.

Rob

**Comment by silentrob** [comment]
I moved this to a dev dependancy in the 0.6 (topics) branch
