### ISSUE TITLE
rename init script to something else

### ISSUE THREAD

**Issue by Delapouite** [silentrob/superscript#67]
Hi

Currently superscript offers a ./bin/init script to scaffold bots.
I had a *very critical* problem with it.

I followed the intructions and install superscript globally : 
`sudo npm install --global superscript` (npm version: 2.5)

Doing so, npm created a new symlink in the `/sbin/` dir `/sbin/init`. It totally replaced the normal init symlink pointing to systemd : my computer could not obviously startup anymore on the next reboot.

I know that one should avoid to install stuff globally but I think this should be safe to rename init to something else (line init-bot) in case of someone else falling into this trap.

**Comment by silentrob** [comment]
Wow, that is not good at all. Thanks for pointing that out, and I hope it wasn't to much of a hassle.

Ill push a change immediately.

**Comment by silentrob** [comment]
Pushed to master. Im actually going to review those scripts in the wake of launching a new GUI editor for bot authoring. This should be done before monday.
