### ISSUE TITLE
facts module loading problem

### ISSUE THREAD

**Issue by makuk66** [silentrob/superscript#69]
Hi,

I tried to follow the "Slack + SuperScript — Rise of the Bots" example, but I ran into trouble.
I'm seeing this with Docker, but a colleague has seen the same outside Docker.
The first problem is that when running the server.js, we get a "Cannot find module 'mongoose" error, which we can work around by installing mongoose or setting the NODE_PATH.
With that fixed, the next error is "TypeError: Object #<Object> has no method 'conceptToList'".
Perhaps these are related.

I tried to replaced the first global superscript install with a separate local install, and that did not make a difference.

This is with Node v0.10.36; I also tried the current 0.12, and that filed to install node-lemmer.

I have provided a test repo with code and more details on https://github.com/makuk66/docker-superscript-slackbot

Any ideas what is going on?

**Comment by makuk66** [comment]
link to github issue

**Comment by silentrob** [comment]
Sorry @makuk66, Development was moving pretty quick and I accident;y broke backward compatibility. Let me see if I can fix it up.

I think I just need to bump a dependancy.

**Comment by silentrob** [comment]
Okay, Im going to close this. I think it is good now. Sorry about that.
init was changed to bot-init.

I also updated the medium post to reflect that change.

**Comment by makuk66** [comment]
Fix confirmed. Thanks!
