### ISSUE TITLE
Parse should support passing in individual files.

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#7]
This is related to GH-6

**Comment by silentrob** [comment]
I have changed my mind on this. If anyone feels this is important. please chime in.

**Comment by dcsan** [comment]
once bots get quite big, it would presumably speed things up to just parse specific files? unless you're already doing that internally with caching?

**Comment by silentrob** [comment]
We are doing that now internally. We cache the file checksums and only re-parse the files that have changed. The drawback to this means that you should structure one file = topic.
