### ISSUE TITLE
TTS and STT suggestions?

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#72]
Do you have some suggestions to connect Superscript with Text to Speech (TTS) and a Speech To Text (STT) systems?

**Comment by silentrob** [comment]
I think it depends on the audience and quality. Nuance, and Google come to mind but honestly I have not fully evaluated the space. 

SuperScript should work with most all of them and drop in easily.

**Comment by airport-transfers** [comment]
I think the same, generally they have them API to connect with. Thanks, good!
