### ISSUE TITLE
Space used from superscript in mongoDB

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#74]
How much space is using a base setup of supsecript in mongodb? And what about the space while using it? Because the price change relatively to the used space too, example: https://cloudant.com/product/pricing/ .

**Comment by silentrob** [comment]
The space required for Mongo completely depends on how many gambits, topics and replies are present. 
I have one example bot still in development that has roughly 30 topics, 1500 Gambits and  3000+ replies sitting at 4.3MB. (including indexes etc).

There is also a few MB of "world data" and fact triples stored in LevelDB - this space would also vary depending on your needs and may be completely optional optional.

Each user is saved in Mongo as well, and we preserve the last 30 messages (replies and messages). I can't imaging it getting terribly out of control.

The entire chat log is written out to disk and that might grow overtime.

Lastly, I'm exploring building a hosted option, and these details should be abstracted away.
