### ISSUE TITLE
Redirecting yes or not

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#75]
Is it possible to write a script like this:
+ hello friend
+ greeting
- Hello
- Ola

Or this is grammatically wrong and I have to use always the redirecting in this case?
 + hello friend
@greeting

+ greeting
- Hello
- Ola

**Comment by silentrob** [comment]
So Github has hijacked your formatting. 
    
    + hello friend
    - greeting
    - Hello
    - Ola

In this example, when the system sees "hello friend" we will randomly pick and reply with "greeting", "Hello", or "Ola". If you say "hello friend" over and over, it will keep plucking out unseen replies until they are all exhausted.

The second example

    + hello friend @greeting

When we see `@greeting` the system will look for another trigger `+ greeting` and append one of those replies.

     + hello friend @greeting

     + greeting
     - hello
     - Ola
  
Notice the greeting in this example is a trigger and the greeting in the first example is a reply.
Hope this helps.
