### ISSUE TITLE
How to exchange data between Superscript and PHP?

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#78]
Could you please show me an example of data exchange between Superscript and PHP?
For example:
1)  show data of registered users/chatters.
2) Save data of registered chatters in the chat
3) Login in the chat of the registered users, and show then them unique custom username in the chat

**Comment by silentrob** [comment]
I'm afraid no example exists for that yet.

You would need to wrap Superscript up in a small server and call it from php via request. 
http://php.net/manual/en/function.file-get-contents.php
