### ISSUE TITLE
Tips about chatbots in different languages?

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#79]
Is there some special configuration to do to change the chat language into a language different from english?
For Example I am interested to build up italian and spanish chatbot too soon.

**Comment by silentrob** [comment]
The bot is currently in english only. It would require a lot of work to change the internals to Italian / spanish. See github.com/silentrob/normalizer to get a sense of what is happening under the hood.

**Comment by airport-transfers** [comment]
I checked the https://github.com/silentrob/normalizer/ pages, and from my side is not impossible to user the other languages, because I am focusing only on some arguments and not on all whole world.
And I need some ideas to clarify:
1) You have done a great work! I think that in the file interjections.txt this line is wrong: <absolutely ~yes
2) about the file british.txt it look that it is useful for example in italian language to add the file switzerland.txt because of the italian language a bit different there and the same for spanish that have many other different variations like caribbena, sourh america, central america or more.
3) canonical.txt is not clear so much to me, could you explain it better, (for example c C, 's  's, be be)
4) systemessentials.txt is not clear to me 
5) test/basic.js not so much clear
6) package.json will  need some changes too?

**Comment by silentrob** [comment]
Thanks.

1. absolutely in the middle of a question or statement would be wrong, however if the first word is absolutely then it converts to ~yes.
2. british.txt is was just designed to map british (commonwealth english) to us english, and is not meant to replace the entire dictionary. 
3. canonical.txt is actually not being used at the moment. This step has been mostly replaced by node-lemma.
4. systemessentials deletes trailing or dangling punct. 
5 and 6. Im not sure what is not clear or needs fixing.
