### ISSUE TITLE
Option to pause the bot and answer with a second human

### ISSUE THREAD

**Issue by airport-transfers** [silentrob/superscript#80]
Do you think that is possible to pause sometimes the bot and make a human to answer instead? Do you have suggestions to add this option?

**Comment by silentrob** [comment]
This is something that I have not implemented or given a ton of thought to. 
So I will do it now...


Okay, you could do something like that with..

    + what is the meaning of life
    - ^askAHuman()

And this function could ask a human, based on some business logic. (business hours, sms, chat etc) If it times-out after 10 seconds, It can skip or reply with something generic...
