### ISSUE TITLE
Redirect (or non-plugin function) in reply prevents plugin function from inserting text

### ISSUE THREAD

**Issue by owenhindley** [silentrob/superscript#81]
Hey!

I have the following:
```
+ tell me a random fact
- {keep} Okay, here's a fact: ^getRandomFact() . {@_post_random_fact}

+ _post_random_fact
- Would you like me to tell you another fact?
```
Where ^getRandomFact() fetches a fact from somewhere online (so can take a while to call back), and inserts that text into the reply. 

I am hoping to get a response like
_Okay, here's a fact: the sky is blue. Would you like me to tell you another fact?_

Instead I'm getting 
_Okay, here's a fact: ^getRandomFact(). Would you like me to tell you another fact?_

Am I doing something wrong? I get the same behaviour if I use ^topicRedirect(xx,yy) instead of {@xxx} - but not if the last function is a custom function (then everything works correctly, but I can't then redirect to a new reply)

Thanks!

**Comment by silentrob** [comment]
I will add a test for this and see what happens. It should work.
I think we are process the redirects first, than the custom functions. (or failing to)

Nice work BTW. It is great to see people doing more than "hello world".

**Comment by silentrob** [comment]
Funny enough, It works the other way around,

    + tell me a random fact two
    - {keep} Okay, here's a fact. {@_post_random_fact}

    + _post_random_fact
    -  ^ getRandomFact() Would you like me to tell you another fact?

It is just an order problem. We are not being recursive on the first part of the reply.
