### ISSUE TITLE
GetReply filters out current topic if it is 'system'

### ISSUE THREAD

**Issue by owenhindley** [silentrob/superscript#83]
Hey,

Not sure if this is intended behaviour, but I'm not getting responses from replies within a system topic, when the user is still within that topic, e.g.:

```
> pre
	+ USER_BEGIN
	- ^topicRedirect(introductions, __start__)
< pre


> topic:system introductions

+ __start__
- What do you want?
^ Have I met you before?

+ [*] ~yes [*]
- Nice to meet you again.

+ [*] ~no [*]
- Fine, good to meet you.


< topic


```

By default, the user agent sends USER_BEGIN at the start of every conversation, which (as far as I understand) in the above code should redirect them to introductions, to say 'what do you want? have I met you before?'

If the user then responds with 'yes', I would expect the 'nice to meet you again' reply to fire, because we've moved into that topic via ^topicRedirect().

What happens instead is we just get a blank string back, and the debug info reports that it's only searching in pre and post.

Looking in topic.js, in findPendingTopicsForUser, it looks like the engine is filtering out any system topics, including the current one - is that right?

Backstory - we're using Superscript to implement a particular narrative / story, so using these system topics in this way (to tightly control which responses are active when) are super useful!

Thanks!
Owen

**Comment by silentrob** [comment]
Thanks for the example and backstory.

I have gone back and forth on this specific behaviour and I'm not positive it is right yet. 
You are right, I am filtering out the system topics, however I feel like if you are in a conversation, it should still match and continue. 

For example:

    > topic:system introductions

    + __start__
    - What do you want? Have I met you before?

    %  What do you want? Have I met you before?
    + [*] ~yes [*]
    - Nice to meet you again.

    %  What do you want? Have I met you before?
    + [*] ~no [*]
    - Fine, good to meet you.

    < topic

This is almost identical to your example, except the YES and NO are contextual to the previous reply. I don't recall of the top of my head if that works as I described, but it ought to. Either way, Im open to suggestions on how to improve this.

Rob

**Comment by owenhindley** [comment]
Hey Rob,

Thanks for the reply! I did start out using the % rejoinder notation to control conversation flow, and it's a great way to create deep 'nested' conversation responses.

However I ended up switching to topic-level control because we were creating a) very long and b) composite responses from two or three groups of similar phrases joined together, e.g.

```
+ __start___
- Hello. {@__response_one__}
- Hi there. {@__response_one__}
- Hey. {@__response_one__}

+ __response_one__
- How are you today? {@__response_two__}
- What's up? {@__response_two__}
- Nice to meet you! {@__response_two__}

+ __response_two_
- Say, what's your name?
- So, what do people call you?

```
(this was because we wanted different users to get a slightly difference experience from each bot)

So to create separate % rejoinders for each of those possibilities would be lots of work, and I was having trouble using wildcards in the rejoinders (otherwise I guess ``` % * do people call you? ``` would work?). This meant I ended up having responses 'per topic', but I still wanted to prevent them from firing elsewhere (e.g. in other topics, where we still might want to have the user answer ~yes or ~no)

I'm going to run for a while with a modified topic.js in our setup here and see how that goes - will let you know - but I understand it might not always be intuitive for new users to have ```system``` responses included in the topic flow when you're in that topic. 

Hope the real-life(ish) use case is useful in some way!

**Comment by silentrob** [comment]
I totally dig the composite responses, they are a great way to create really dynamic replies and add variance. You can also push them a little further by added filter functions. So your `__responce_two_` could check to see if you know the name already. That point is moot, if this is the first thing said.

You are right composite responses and nested replies `%` don't mix because of how the previous reply matches, (it is too strict) more work could be done here to improve that, and either partial or wildcards matches might work. 

It seems like you are needed a little more flow control, as you are already poking the script with "USER BEGIN" to kick things off. Something like...
 
    > pre
      + {^firstReply()} *
      - ^topicRedirect(introductions, __start__)
    < pre

where firstReply might simply be:

    exports.firstReply = function(next) {
      next(null, (this.user.__history__.input.length === 0))
    }

Lastly, we can also put a flag on the system topic to negate the filter flow behaviour.

**Comment by silentrob** [comment]
I have also been toying with the idea of exposing some global variables directly to the scripting interface, but that is really only useful if you have a way to do inline conditionals. 

Things like `$REPLYCOUNT` and `$RAND` come to mind, but I don't see huge wins over a collections of utility functions (plugins) and documentation.

**Comment by owenhindley** [comment]
I completely agree - having this powerful plugin architecture to control the flow + filter out functions has been really useful, and keeps the actual scripting language simpler and easier to read, which is always good :) I think it's a better approach than having global constants all over the place.

It's still a little bit awkward however to create complex response 'trees' - compared to (in this specific case) ChatScript's method of having responses that are checked directly after a particular gambit and reply from the user - almost like 'micro-topics', that you can declare inline. Maybe there could be a case for a bit of syntactic sugar that groups a set of replies to be 'active' only after a particular response has been fired, something like this?

```
+ __start___
- Do you like ^randomFruit() ? // assuming this would be a complex gambit, that would be tricky to match via % operator

>> ~yes
- Great! I'm a big fan myself. {@_next_question_}

>> ~no
- Oh, that's a shame - they're very good for you, you know. {@_next_question_}

+ _next_question_
- Okay, what about ^randomVegetable()? // likewise

>> ~yes
- Can't stand vegetables, me. 

>> ~no
- Yep, I'm with you - fruit and meat all the way!

```

Where some sort of operand (I've used >> here as an example) would create a mini-topic that only became active for checking immediately after the user had responded to the gambit above. Just a thought..

**Comment by silentrob** [comment]
Funny, I just mentioned this in GH-86. Internally, the reply model and gambit model form a full tree and really there is really not much difference between a topic and a reply except how they are initially matched. 

Topics by keywords, and Replies by previous conversation, and they are activated and checked first before looking elsewhere.

So I believe once GH-84 and GH-86 are resolved that should work as described - unless Im missing something.

Also, thanks for the comparison to CS. My goal all along was to create a scripting lang with the ease of use as RS and the power of CS. (or close too) So it is nice to be mentioned along side.

**Comment by silentrob** [comment]
@owenhindley With GH-84 and GH-86 now closed you should be unblocked. Im tracking one more low risk change and will publish a new version.

Your suggestion for `>>` is really a shorthand notation for

    + __start___
    - Do you like ^randomFruit() ? // assuming this would be a complex gambit, that would be tricky to match via % operator

    + ~yes
    %  *
    - Great! I'm a big fan myself. {@_next_question_}

    + ~no
    % *
    - Oh, that's a shame - they're very good for you, you know. {@_next_question_}

I like the idea of tightening this up more.

**Comment by silentrob** [comment]
@owenhindley Im not sure there is an issue here anymore. I'm going to close this and we can discus further on slack if you would like to see the functionality changed.
