### ISSUE TITLE
Keep matching after a match is found.

### ISSUE THREAD

**Issue by silentrob** [silentrob/superscript#93]
There may be a need to match and continue searching for matches within the same message

    + * ~yes *
    -  {continue} sure

    + * add *~4 cart *
    - I will

    > okay, ya I like that and add it to my cart
    < sure I will

So `{continue}` will keep searching for a match, and the default behaviour is to end and return.

**Comment by silentrob** [comment]
So to expand on this a little more, perhaps we could introduce `{continue}` `{continue-all}` and `{continue-global}` Which would continue to the end of the topic, continue though ALL topics, and continue to all topics and system topics (global).

**Comment by mariusursache** [comment]
@silentrob Is this still an issue, after the conversation enhancement?
