### ISSUE TITLE
bot pulls replies from DB even after a recompilation

### ISSUE THREAD

**Issue by ganarajpr** [silentrob/superscript#95]
So, I was trying to create a bot script and the problem was that even after I `parse -f` and then restarted the node server - the bot was still replying the old replies. No matter what I tried - it would not reply back the corrected new replies. 

I debugged it to be that somehow the bot was pulling replies from the mongo database as opposed to the new `data.json` file ? Seemed to work fine after I did `db.replies.remove({})`

**Comment by silentrob** [comment]
Ya, sorry about that. I just bumped into that as well. I'm not completely sure what the right fix is for that. The JSON file was the model for the longest time, but we have since moved that "truth" to mongo, and we import the JSON without merging or cleanly deleting it prior (it assumes a clean db).

We can either do a findOrCreate on the gambits, or have a nice way to delete the model prior to importing it.

**Comment by ganarajpr** [comment]
Also on a side note - have  you considered using something like 
https://github.com/mcollina/levelgraph

a graphdb for the fact system ?

**Comment by ganarajpr** [comment]
Here is the fix I had to do make it a simple one step process again.. 

`file cleardb.js`

```javascript
var MongoClient = require('mongodb').MongoClient
    , assert = require('assert');

// Connection URL
var url = 'mongodb://localhost:27017/superscriptDB';
// Use connect method to connect to the Server
MongoClient.connect(url, function(err, db) {
    assert.equal(null, err);
    console.log("Connected correctly to server");
    removeDocument(db,function(){
        db.close();
    });
});


var removeDocument = function(db, callback) {
    // Get the documents collection
    var users = db.collection('users');
    var topics = db.collection('topics');
    var replies = db.collection('replies');

    users.remove({},function(err,res){
        console.log(res);
    });
    topics.remove({},function(err,res){
        console.log(res);
    });
    replies.remove({},function(err,res){
        console.log(res);
    });

    callback();

};
```

Also this is the shell script I use to start the bot. 

```sh
parse -f
node cleardb.js
rm -rf telnetFacts/*
rm -rf systemDB/*
rm -rf botfacts/*
node telnet.js
```

**Comment by silentrob** [comment]
We now have a `/bin/cleanup.js` thanks to @ganarajpr and @Laurian.
