### ISSUE TITLE
Not clear how to use plugins / custom functions ?

### ISSUE THREAD

**Issue by ganarajpr** [silentrob/superscript#96]
I created a new file in the plugins directory ( created by bot-init ). Exported a new function and tried accessing it in the .ss file. That doesnt seem to work for some reason ? Do you have any working example for this ?

**Comment by silentrob** [comment]
The plugins should be automatically imported from the global plugin folder, than the local folder. 

You can see an example of that here - https://github.com/silentrob/superscript-websocket-demo
Also when you start the client with DEBUG=Script* node server.js  or whatever your entry point is, you will see all the plugins loaded.
