### ISSUE TITLE
Flow is not clear

### ISSUE THREAD

**Issue by ganarajpr** [silentrob/superscript#97]
I created a ss file which looks something like this : 

```
+ hi
- Hi. Welcome to macy's. 
^ How can I address you as?{topic=newcustomer}

> topic newcustomer
+ *1
- ^addCustomer(<cap>).
^ Hi <cap>. Can I take your order? {topic=order}
< topic

> topic order
+ (*)
- ordered <cap>. ^storeOrder(<cap>)
< topic

```

The idea is to flow from the initial conversation to `newcustomer` topic to `order` topic. This doesnt seem to work as expected ( perhaps because both `newcustomer` and `order` have `(*)` ? ) . My expectation is that once I change the topic to `order`, it should only match things in `order` and not even look in `newcustomer` ? 

With this ss file I expect a conversation like this : 

```
hi
- Hi. Welcome to macy's. How can I address you as ?
jack
- Hi Jack. Can I take your order ?
pizza
- ordered pizza.
```
But I believe it goes to 

`- Hi pizza. Can I take your order ? `

**Comment by silentrob** [comment]
So I would avoid using `{topic=...}` All this does is sets the recommended next topic on the next reply but does not guarantee a mach. You could also get false positive matches out of context. 

Instead you will probably want to use a conversation rely.

    + hi
    - Hi. Welcome to macy's. 
    ^ How can I address you as?

      + *1
      % * How can I address you as?  
      - ^addCustomer(<cap>).
      ^ Hi <cap>. Can I take your order?
        
        + (*)
        % * Can I take your order?
        - ordered <cap>. ^storeOrder(<cap>)

**Comment by ganarajpr** [comment]
Ok. I will test this out tonight and let you know. Thanks for that. This example also showed me how I could use wildcards in `%` style conversations. In your documentation, that was not clear and I did not know I could do that.

**Comment by ganarajpr** [comment]
Hmmm.. I went ahead and had a look at the documentation page . The conversation example looks like this :

```
  % What is your favorite color?
  + *1
  - <cap> is mine too.
```

While in your example above the order of `%` and `+` is reversed. Which order is right ? Or does the order not matter ?

**Comment by silentrob** [comment]
Sorry, the docs have it backwards. Ill push out an update. 

Here is the tests examples 
https://github.com/silentrob/superscript/blob/master/test/fixtures/continue/main.ss
